/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "dump_cb.h"
#include "dump_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ramdump_fileselection (void)
{
  GtkWidget *ramdump_fileselection;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  ramdump_fileselection = gtk_file_selection_new (_("Select a ROM to load"));
  gtk_container_set_border_width (GTK_CONTAINER (ramdump_fileselection), 10);
  gtk_window_set_modal (GTK_WINDOW (ramdump_fileselection), TRUE);

  ok_button2 = GTK_FILE_SELECTION (ramdump_fileselection)->ok_button;
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (ramdump_fileselection)->cancel_button;
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) ramdump_fileselection, "destroy",
                    G_CALLBACK (on_ramdump_fileselection_destroy),
                    NULL);
  g_signal_connect ((gpointer) ok_button2, "clicked",
                    G_CALLBACK (on_ramd_ok_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button2, "clicked",
                    G_CALLBACK (on_ramd_cancel_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ramdump_fileselection, ramdump_fileselection, "ramdump_fileselection");
  GLADE_HOOKUP_OBJECT_NO_REF (ramdump_fileselection, ok_button2, "ok_button2");
  GLADE_HOOKUP_OBJECT_NO_REF (ramdump_fileselection, cancel_button2, "cancel_button2");

  gtk_window_add_accel_group (GTK_WINDOW (ramdump_fileselection), accel_group);

  return ramdump_fileselection;
}

GtkWidget*
create_romdump_fileselection (void)
{
  GtkWidget *romdump_fileselection;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  romdump_fileselection = gtk_file_selection_new (_("Select a ROM to load"));
  gtk_container_set_border_width (GTK_CONTAINER (romdump_fileselection), 10);
  gtk_window_set_modal (GTK_WINDOW (romdump_fileselection), TRUE);

  ok_button2 = GTK_FILE_SELECTION (romdump_fileselection)->ok_button;
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (romdump_fileselection)->cancel_button;
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) romdump_fileselection, "destroy",
                    G_CALLBACK (on_romd_fileselection_destroy),
                    NULL);
  g_signal_connect ((gpointer) ok_button2, "clicked",
                    G_CALLBACK (on_romd_ok_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button2, "clicked",
                    G_CALLBACK (on_romd_cancel_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (romdump_fileselection, romdump_fileselection, "romdump_fileselection");
  GLADE_HOOKUP_OBJECT_NO_REF (romdump_fileselection, ok_button2, "ok_button2");
  GLADE_HOOKUP_OBJECT_NO_REF (romdump_fileselection, cancel_button2, "cancel_button2");

  gtk_window_add_accel_group (GTK_WINDOW (romdump_fileselection), accel_group);

  return romdump_fileselection;
}

GtkWidget*
create_wait_conversion_dbox (void)
{
  GtkWidget *wait_conversion_dbox;
  GtkWidget *label1;

  wait_conversion_dbox = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wait_conversion_dbox), _("In progress..."));

  label1 = gtk_label_new (_("File is being written. \nPlease wait..."));
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (wait_conversion_dbox), label1);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 10, 10);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wait_conversion_dbox, wait_conversion_dbox, "wait_conversion_dbox");
  GLADE_HOOKUP_OBJECT (wait_conversion_dbox, label1, "label1");

  return wait_conversion_dbox;
}

