/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "link_cb.h"
#include "link_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_linktype_dbox (void)
{
  GtkWidget *linktype_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *frame4;
  GtkWidget *table3;
  GtkWidget *button1;
  GtkWidget *label2;
  GtkWidget *label8;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label7;
  GtkWidget *frame3;
  GtkWidget *hbox1;
  GtkWidget *button2;
  GtkWidget *label9;
  GtkWidget *frame1;
  GtkWidget *table2;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton7;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton1;
  GtkWidget *radiobutton5;
  GtkWidget *label10;
  GtkWidget *frame2;
  GtkWidget *vbox2;
  GtkWidget *radiobutton10;
  GSList *radiobutton10_group = NULL;
  GtkWidget *radiobutton11;
  GtkWidget *radiobutton12;
  GtkWidget *radiobutton13;
  GtkWidget *radiobutton14;
  GtkWidget *label11;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *cancel_button;
  GtkWidget *ok_button;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  linktype_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (linktype_dbox), _("Configuration of the link cable and I/O ports"));

  dialog_vbox1 = GTK_DIALOG (linktype_dbox)->vbox;
  gtk_widget_show (dialog_vbox1);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, FALSE, TRUE, 0);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_table_attach (GTK_TABLE (table1), frame4, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 5);

  table3 = gtk_table_new (2, 3, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (frame4), table3);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 5);

  button1 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (button1);
  gtk_table_attach (GTK_TABLE (table3), button1, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label2 = gtk_label_new (_("I/O address:"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table3), label2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  label8 = gtk_label_new (_("I/O device:"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table3), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label8), 5, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table3), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("*****"));

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table3), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("/dev/"));

  label7 = gtk_label_new (_("Specify I/O or device:"));
  gtk_widget_show (label7);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label7);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_table_attach (GTK_TABLE (table1), frame3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 5);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (frame3), hbox1);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 10);

  button2 = gtk_button_new_with_mnemonic (_("Click Here"));
  gtk_widget_show (button2);
  gtk_box_pack_end (GTK_BOX (hbox1), button2, FALSE, FALSE, 0);

  label9 = gtk_label_new (_("Probing of ports & cables"));
  gtk_widget_show (label9);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label9);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_table_attach (GTK_TABLE (table1), frame1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);

  table2 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (frame1), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 5);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("TIEmulator virtual link"));
  gtk_widget_show (radiobutton3);
  gtk_table_attach (GTK_TABLE (table2), radiobutton3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Home-made parallel"));
  gtk_widget_show (radiobutton2);
  gtk_table_attach (GTK_TABLE (table2), radiobutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("TI/PC USB link"));
  gtk_widget_show (radiobutton4);
  gtk_table_attach (GTK_TABLE (table2), radiobutton4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("AVRlink"));
  gtk_widget_show (radiobutton6);
  gtk_table_attach (GTK_TABLE (table2), radiobutton6, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("VTi virtual link"));
  gtk_widget_show (radiobutton7);
  gtk_table_attach (GTK_TABLE (table2), radiobutton7, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("TIGraphLink USB"));
  gtk_widget_show (radiobutton8);
  gtk_table_attach (GTK_TABLE (table2), radiobutton8, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Grey TIGraphLink\nAVRLink"));
  gtk_widget_show (radiobutton1);
  gtk_table_attach (GTK_TABLE (table2), radiobutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Black TIGraphLink\nHome-made serial"));
  gtk_widget_show (radiobutton5);
  gtk_table_attach (GTK_TABLE (table2), radiobutton5, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  label10 = gtk_label_new (_("Link cable type:"));
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label10);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_table_attach (GTK_TABLE (table1), frame2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame2), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 5);

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("Serial port #1"));
  gtk_widget_show (radiobutton10);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton10, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton10), TRUE);

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("Serial port #2"));
  gtk_widget_show (radiobutton11);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton11, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, _("Serial port #3"));
  gtk_widget_show (radiobutton12);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton12, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  radiobutton13 = gtk_radio_button_new_with_mnemonic (NULL, _("Serial port #4"));
  gtk_widget_show (radiobutton13);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton13, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton13), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton13));

  radiobutton14 = gtk_radio_button_new_with_mnemonic (NULL, _("Custom settings"));
  gtk_widget_show (radiobutton14);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton14, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  label11 = gtk_label_new (_("I/O port:"));
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label11);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);

  dialog_action_area1 = GTK_DIALOG (linktype_dbox)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area1), hbuttonbox1);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  cancel_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cancel_button);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), ok_button);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_linktype_button_fs_clicked),
                    NULL);
  g_signal_connect ((gpointer) entry1, "changed",
                    G_CALLBACK (linktype_entry1_changed),
                    NULL);
  g_signal_connect ((gpointer) entry2, "changed",
                    G_CALLBACK (linktype_entry2_changed),
                    NULL);
  g_signal_connect ((gpointer) button2, "pressed",
                    G_CALLBACK (on_button2_pressed),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (linktype_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (linktype_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (linktype_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (linktype_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (linktype_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton8, "toggled",
                    G_CALLBACK (linktype_radiobutton8_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (linktype_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (linktype_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton10, "toggled",
                    G_CALLBACK (linktype_radiobutton10_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton11, "toggled",
                    G_CALLBACK (linktype_radiobutton11_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton12, "toggled",
                    G_CALLBACK (linktype_radiobutton12_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton13, "toggled",
                    G_CALLBACK (linktype_radiobutton13_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton14, "toggled",
                    G_CALLBACK (linktype_radiobutton14_toggled),
                    NULL);
  g_signal_connect ((gpointer) cancel_button, "clicked",
                    G_CALLBACK (linktype_cancel_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) ok_button, "clicked",
                    G_CALLBACK (linktype_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (linktype_dbox, linktype_dbox, "linktype_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (linktype_dbox, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, table1, "table1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (linktype_dbox, table3, "table3");
  GLADE_HOOKUP_OBJECT (linktype_dbox, button1, "button1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, label2, "label2");
  GLADE_HOOKUP_OBJECT (linktype_dbox, label8, "label8");
  GLADE_HOOKUP_OBJECT (linktype_dbox, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (linktype_dbox, label7, "label7");
  GLADE_HOOKUP_OBJECT (linktype_dbox, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (linktype_dbox, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, button2, "button2");
  GLADE_HOOKUP_OBJECT (linktype_dbox, label9, "label9");
  GLADE_HOOKUP_OBJECT (linktype_dbox, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, table2, "table2");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (linktype_dbox, label10, "label10");
  GLADE_HOOKUP_OBJECT (linktype_dbox, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (linktype_dbox, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton13, "radiobutton13");
  GLADE_HOOKUP_OBJECT (linktype_dbox, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (linktype_dbox, label11, "label11");
  GLADE_HOOKUP_OBJECT_NO_REF (linktype_dbox, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (linktype_dbox, cancel_button, "cancel_button");
  GLADE_HOOKUP_OBJECT (linktype_dbox, ok_button, "ok_button");

  gtk_window_add_accel_group (GTK_WINDOW (linktype_dbox), accel_group);

  return linktype_dbox;
}

GtkWidget*
create_fileselection_device (void)
{
  GtkWidget *fileselection_device;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_device = gtk_file_selection_new (_("Select File"));
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_device), 10);

  ok_button1 = GTK_FILE_SELECTION (fileselection_device)->ok_button;
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button1 = GTK_FILE_SELECTION (fileselection_device)->cancel_button;
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) ok_button1, "clicked",
                    G_CALLBACK (on_seldev_ok_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button1, "clicked",
                    G_CALLBACK (on_seldev_cancel_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection_device, fileselection_device, "fileselection_device");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection_device, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection_device, cancel_button1, "cancel_button1");

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_device), accel_group);

  return fileselection_device;
}

