/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "pgmentbkpt_cb.h"
#include "pgmentbkpt_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_pgmentrybkpt_dbox (void)
{
  GtkWidget *pgmentrybkpt_dbox;
  GtkWidget *vbox22;
  GtkWidget *vbox23;
  GtkWidget *label23;
  GtkWidget *vbox24;
  GtkWidget *list3;
  GtkWidget *hbox4;
  GtkWidget *hbuttonbox5;
  GtkWidget *button22;
  GtkWidget *button21;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  pgmentrybkpt_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (pgmentrybkpt_dbox), _("Program entry breakpoint"));

  vbox22 = GTK_DIALOG (pgmentrybkpt_dbox)->vbox;
  gtk_widget_show (vbox22);

  vbox23 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox23);
  gtk_box_pack_start (GTK_BOX (vbox22), vbox23, TRUE, TRUE, 0);

  label23 = gtk_label_new (_("Select program in which \nto set breakpoint"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (vbox23), label23, FALSE, FALSE, 3);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label23), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label23), 10, 0);

  vbox24 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox24);
  gtk_box_pack_start (GTK_BOX (vbox23), vbox24, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox24), 7);

  list3 = gtk_tree_view_new ();
  gtk_widget_show (list3);
  gtk_box_pack_start (GTK_BOX (vbox24), list3, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (list3, GTK_CAN_FOCUS);

  hbox4 = GTK_DIALOG (pgmentrybkpt_dbox)->action_area;
  gtk_widget_show (hbox4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbox4), GTK_BUTTONBOX_END);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox5);
  gtk_container_add (GTK_CONTAINER (hbox4), hbuttonbox5);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox5), 30);

  button22 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button22);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button22);
  GTK_WIDGET_SET_FLAGS (button22, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button22, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  button21 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button21);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button21);
  GTK_WIDGET_SET_FLAGS (button21, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button21, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) pgmentrybkpt_dbox, "destroy",
                    G_CALLBACK (on_pgmentrybkpt_dbox_destroy),
                    NULL);
  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_button22_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_button21_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pgmentrybkpt_dbox, pgmentrybkpt_dbox, "pgmentrybkpt_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (pgmentrybkpt_dbox, vbox22, "vbox22");
  GLADE_HOOKUP_OBJECT (pgmentrybkpt_dbox, vbox23, "vbox23");
  GLADE_HOOKUP_OBJECT (pgmentrybkpt_dbox, label23, "label23");
  GLADE_HOOKUP_OBJECT (pgmentrybkpt_dbox, vbox24, "vbox24");
  GLADE_HOOKUP_OBJECT (pgmentrybkpt_dbox, list3, "list3");
  GLADE_HOOKUP_OBJECT_NO_REF (pgmentrybkpt_dbox, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (pgmentrybkpt_dbox, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (pgmentrybkpt_dbox, button22, "button22");
  GLADE_HOOKUP_OBJECT (pgmentrybkpt_dbox, button21, "button21");

  gtk_window_add_accel_group (GTK_WINDOW (pgmentrybkpt_dbox), accel_group);

  return pgmentrybkpt_dbox;
}

