/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "trap_cb.h"
#include "trap_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_trap_dbox (void)
{
  GtkWidget *trap_dbox;
  GtkWidget *dialog_vbox13;
  GtkWidget *table3;
  GtkWidget *frame25;
  GtkWidget *table4;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *checkbutton8;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton9;
  GtkWidget *label3;
  GtkWidget *frame26;
  GtkWidget *vbox33;
  GtkWidget *checkbutton10;
  GtkWidget *checkbutton11;
  GtkWidget *checkbutton12;
  GtkWidget *checkbutton13;
  GtkWidget *checkbutton15;
  GtkWidget *checkbutton14;
  GtkWidget *label4;
  GtkWidget *frame27;
  GtkWidget *table5;
  GtkWidget *checkbutton16;
  GtkWidget *checkbutton17;
  GtkWidget *checkbutton18;
  GtkWidget *checkbutton19;
  GtkWidget *checkbutton20;
  GtkWidget *checkbutton21;
  GtkWidget *checkbutton22;
  GtkWidget *checkbutton23;
  GtkWidget *checkbutton24;
  GtkWidget *checkbutton25;
  GtkWidget *checkbutton26;
  GtkWidget *checkbutton27;
  GtkWidget *checkbutton28;
  GtkWidget *checkbutton29;
  GtkWidget *checkbutton30;
  GtkWidget *checkbutton31;
  GtkWidget *label5;
  GtkWidget *dialog_action_area13;
  GtkWidget *hbuttonbox17;
  GtkWidget *button47;
  GtkWidget *button46;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  trap_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (trap_dbox), _("Bkreakpoint on trap/exception"));

  dialog_vbox13 = GTK_DIALOG (trap_dbox)->vbox;
  gtk_widget_show (dialog_vbox13);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox13), table3, TRUE, TRUE, 0);

  frame25 = gtk_frame_new (NULL);
  gtk_widget_show (frame25);
  gtk_table_attach (GTK_TABLE (table3), frame25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame25), 5);

  table4 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame25), table4);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Adress error"));
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table4), checkbutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Illegal instruction"));
  gtk_widget_show (checkbutton3);
  gtk_table_attach (GTK_TABLE (table4), checkbutton3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Divide by zero"));
  gtk_widget_show (checkbutton4);
  gtk_table_attach (GTK_TABLE (table4), checkbutton4, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("CHK instruction"));
  gtk_widget_show (checkbutton5);
  gtk_table_attach (GTK_TABLE (table4), checkbutton5, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("TRAPV instruction"));
  gtk_widget_show (checkbutton6);
  gtk_table_attach (GTK_TABLE (table4), checkbutton6, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("Trace"));
  gtk_widget_show (checkbutton7);
  gtk_table_attach (GTK_TABLE (table4), checkbutton7, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton8 = gtk_check_button_new_with_mnemonic (_("Line 1010 emulator"));
  gtk_widget_show (checkbutton8);
  gtk_table_attach (GTK_TABLE (table4), checkbutton8, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Privilege violation"));
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table4), checkbutton2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton9 = gtk_check_button_new_with_mnemonic (_("Line 1111 emulator"));
  gtk_widget_show (checkbutton9);
  gtk_table_attach (GTK_TABLE (table4), checkbutton9, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label3 = gtk_label_new (_("Exceptions"));
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (frame25), label3);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  frame26 = gtk_frame_new (NULL);
  gtk_widget_show (frame26);
  gtk_table_attach (GTK_TABLE (table3), frame26, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame26), 5);

  vbox33 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox33);
  gtk_container_add (GTK_CONTAINER (frame26), vbox33);

  checkbutton10 = gtk_check_button_new_with_mnemonic (_("Auto-int 1 (350 Hz timer)"));
  gtk_widget_show (checkbutton10);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton10, FALSE, FALSE, 0);

  checkbutton11 = gtk_check_button_new_with_mnemonic (_("Auto-int 2 (keyboard)"));
  gtk_widget_show (checkbutton11);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton11, FALSE, FALSE, 0);

  checkbutton12 = gtk_check_button_new_with_mnemonic (_("Auto-int 4 (link)"));
  gtk_widget_show (checkbutton12);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton12, FALSE, FALSE, 0);

  checkbutton13 = gtk_check_button_new_with_mnemonic (_("Auto-int 5 (prog timer)"));
  gtk_widget_show (checkbutton13);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton13, FALSE, FALSE, 0);

  checkbutton15 = gtk_check_button_new_with_mnemonic (_("Auto-int 6 (on key)"));
  gtk_widget_show (checkbutton15);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton15, FALSE, FALSE, 0);

  checkbutton14 = gtk_check_button_new_with_mnemonic (_("Auto-int 7 (protected mem)"));
  gtk_widget_show (checkbutton14);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton14, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("Auto-ints"));
  gtk_widget_show (label4);
  gtk_frame_set_label_widget (GTK_FRAME (frame26), label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  frame27 = gtk_frame_new (NULL);
  gtk_widget_show (frame27);
  gtk_table_attach (GTK_TABLE (table3), frame27, 0, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame27), 5);

  table5 = gtk_table_new (4, 4, FALSE);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (frame27), table5);

  checkbutton16 = gtk_check_button_new_with_mnemonic (_("Trap 0"));
  gtk_widget_show (checkbutton16);
  gtk_table_attach (GTK_TABLE (table5), checkbutton16, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton17 = gtk_check_button_new_with_mnemonic (_("Trap 1 (int mask)"));
  gtk_widget_show (checkbutton17);
  gtk_table_attach (GTK_TABLE (table5), checkbutton17, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton18 = gtk_check_button_new_with_mnemonic (_("Trap 2 (reset)"));
  gtk_widget_show (checkbutton18);
  gtk_table_attach (GTK_TABLE (table5), checkbutton18, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton19 = gtk_check_button_new_with_mnemonic (_("Trap 3"));
  gtk_widget_show (checkbutton19);
  gtk_table_attach (GTK_TABLE (table5), checkbutton19, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton20 = gtk_check_button_new_with_mnemonic (_("Trap 4 (on/off)"));
  gtk_widget_show (checkbutton20);
  gtk_table_attach (GTK_TABLE (table5), checkbutton20, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton21 = gtk_check_button_new_with_mnemonic (_("Trap 5"));
  gtk_widget_show (checkbutton21);
  gtk_table_attach (GTK_TABLE (table5), checkbutton21, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton22 = gtk_check_button_new_with_mnemonic (_("Trap 6"));
  gtk_widget_show (checkbutton22);
  gtk_table_attach (GTK_TABLE (table5), checkbutton22, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton23 = gtk_check_button_new_with_mnemonic (_("Trap 7"));
  gtk_widget_show (checkbutton23);
  gtk_table_attach (GTK_TABLE (table5), checkbutton23, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton24 = gtk_check_button_new_with_mnemonic (_("Trap 8"));
  gtk_widget_show (checkbutton24);
  gtk_table_attach (GTK_TABLE (table5), checkbutton24, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton25 = gtk_check_button_new_with_mnemonic (_("Trap 9"));
  gtk_widget_show (checkbutton25);
  gtk_table_attach (GTK_TABLE (table5), checkbutton25, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton26 = gtk_check_button_new_with_mnemonic (_("Trap 10 (self test)"));
  gtk_widget_show (checkbutton26);
  gtk_table_attach (GTK_TABLE (table5), checkbutton26, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton27 = gtk_check_button_new_with_mnemonic (_("Trap 11 (archive)"));
  gtk_widget_show (checkbutton27);
  gtk_table_attach (GTK_TABLE (table5), checkbutton27, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton28 = gtk_check_button_new_with_mnemonic (_("Trap 12"));
  gtk_widget_show (checkbutton28);
  gtk_table_attach (GTK_TABLE (table5), checkbutton28, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton29 = gtk_check_button_new_with_mnemonic (_("Trap 13"));
  gtk_widget_show (checkbutton29);
  gtk_table_attach (GTK_TABLE (table5), checkbutton29, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton30 = gtk_check_button_new_with_mnemonic (_("Trap 14"));
  gtk_widget_show (checkbutton30);
  gtk_table_attach (GTK_TABLE (table5), checkbutton30, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton31 = gtk_check_button_new_with_mnemonic (_("Trap 15 (ER_throw)"));
  gtk_widget_show (checkbutton31);
  gtk_table_attach (GTK_TABLE (table5), checkbutton31, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("Traps"));
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (frame27), label5);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  dialog_action_area13 = GTK_DIALOG (trap_dbox)->action_area;
  gtk_widget_show (dialog_action_area13);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area13), GTK_BUTTONBOX_END);

  hbuttonbox17 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox17);
  gtk_container_add (GTK_CONTAINER (dialog_action_area13), hbuttonbox17);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox17), 30);

  button47 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button47);
  gtk_container_add (GTK_CONTAINER (hbuttonbox17), button47);
  GTK_WIDGET_SET_FLAGS (button47, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button47, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  button46 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button46);
  gtk_container_add (GTK_CONTAINER (hbuttonbox17), button46);
  GTK_WIDGET_SET_FLAGS (button46, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button46, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5, "toggled",
                    G_CALLBACK (on_checkbutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton6, "toggled",
                    G_CALLBACK (on_checkbutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton7, "toggled",
                    G_CALLBACK (on_checkbutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton8, "toggled",
                    G_CALLBACK (on_checkbutton8_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton9, "toggled",
                    G_CALLBACK (on_checkbutton9_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton10, "toggled",
                    G_CALLBACK (on_checkbutton10_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton11, "toggled",
                    G_CALLBACK (on_checkbutton11_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton12, "toggled",
                    G_CALLBACK (on_checkbutton12_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton13, "toggled",
                    G_CALLBACK (on_checkbutton13_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton15, "toggled",
                    G_CALLBACK (on_checkbutton15_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton14, "toggled",
                    G_CALLBACK (on_checkbutton14_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton16, "toggled",
                    G_CALLBACK (on_checkbutton16_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton17, "toggled",
                    G_CALLBACK (on_checkbutton17_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton18, "toggled",
                    G_CALLBACK (on_checkbutton18_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton19, "toggled",
                    G_CALLBACK (on_checkbutton19_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton20, "toggled",
                    G_CALLBACK (on_checkbutton20_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton21, "toggled",
                    G_CALLBACK (on_checkbutton21_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton22, "toggled",
                    G_CALLBACK (on_checkbutton22_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton23, "toggled",
                    G_CALLBACK (on_checkbutton23_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton24, "toggled",
                    G_CALLBACK (on_checkbutton24_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton25, "toggled",
                    G_CALLBACK (on_checkbutton25_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton26, "toggled",
                    G_CALLBACK (on_checkbutton26_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton27, "toggled",
                    G_CALLBACK (on_checkbutton27_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton28, "toggled",
                    G_CALLBACK (on_checkbutton28_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton29, "toggled",
                    G_CALLBACK (on_checkbutton29_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton30, "toggled",
                    G_CALLBACK (on_checkbutton30_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton31, "toggled",
                    G_CALLBACK (on_checkbutton31_toggled),
                    NULL);
  g_signal_connect ((gpointer) button47, "clicked",
                    G_CALLBACK (on_button47_clicked),
                    NULL);
  g_signal_connect ((gpointer) button46, "clicked",
                    G_CALLBACK (on_button46_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (trap_dbox, trap_dbox, "trap_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (trap_dbox, dialog_vbox13, "dialog_vbox13");
  GLADE_HOOKUP_OBJECT (trap_dbox, table3, "table3");
  GLADE_HOOKUP_OBJECT (trap_dbox, frame25, "frame25");
  GLADE_HOOKUP_OBJECT (trap_dbox, table4, "table4");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton8, "checkbutton8");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton9, "checkbutton9");
  GLADE_HOOKUP_OBJECT (trap_dbox, label3, "label3");
  GLADE_HOOKUP_OBJECT (trap_dbox, frame26, "frame26");
  GLADE_HOOKUP_OBJECT (trap_dbox, vbox33, "vbox33");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton10, "checkbutton10");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton11, "checkbutton11");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton12, "checkbutton12");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton13, "checkbutton13");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton15, "checkbutton15");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton14, "checkbutton14");
  GLADE_HOOKUP_OBJECT (trap_dbox, label4, "label4");
  GLADE_HOOKUP_OBJECT (trap_dbox, frame27, "frame27");
  GLADE_HOOKUP_OBJECT (trap_dbox, table5, "table5");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton16, "checkbutton16");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton17, "checkbutton17");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton18, "checkbutton18");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton19, "checkbutton19");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton20, "checkbutton20");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton21, "checkbutton21");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton22, "checkbutton22");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton23, "checkbutton23");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton24, "checkbutton24");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton25, "checkbutton25");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton26, "checkbutton26");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton27, "checkbutton27");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton28, "checkbutton28");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton29, "checkbutton29");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton30, "checkbutton30");
  GLADE_HOOKUP_OBJECT (trap_dbox, checkbutton31, "checkbutton31");
  GLADE_HOOKUP_OBJECT (trap_dbox, label5, "label5");
  GLADE_HOOKUP_OBJECT_NO_REF (trap_dbox, dialog_action_area13, "dialog_action_area13");
  GLADE_HOOKUP_OBJECT (trap_dbox, hbuttonbox17, "hbuttonbox17");
  GLADE_HOOKUP_OBJECT (trap_dbox, button47, "button47");
  GLADE_HOOKUP_OBJECT (trap_dbox, button46, "button46");

  gtk_window_add_accel_group (GTK_WINDOW (trap_dbox), accel_group);

  return trap_dbox;
}

