/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "user_cb.h"
#include "user_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_user1_dbox (void)
{
  GtkWidget *user1_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *label2;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox7;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  user1_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (user1_dbox), _("Title1"));
  gtk_window_set_modal (GTK_WINDOW (user1_dbox), TRUE);

  dialog_vbox1 = GTK_DIALOG (user1_dbox)->vbox;
  gtk_widget_show (dialog_vbox1);

  label2 = gtk_label_new (_("Message."));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label2), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 5);

  dialog_action_area1 = GTK_DIALOG (user1_dbox)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area1), hbuttonbox1);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox7);

  image1 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox7), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("b1"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox7), label1, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (user1_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (user1_dbox, user1_dbox, "user1_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (user1_dbox, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (user1_dbox, label2, "label2");
  GLADE_HOOKUP_OBJECT_NO_REF (user1_dbox, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (user1_dbox, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (user1_dbox, button1, "button1");
  GLADE_HOOKUP_OBJECT (user1_dbox, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (user1_dbox, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (user1_dbox, image1, "image1");
  GLADE_HOOKUP_OBJECT (user1_dbox, label1, "label1");

  gtk_window_add_accel_group (GTK_WINDOW (user1_dbox), accel_group);

  return user1_dbox;
}

GtkWidget*
create_user2_dbox (void)
{
  GtkWidget *user2_dbox;
  GtkWidget *dialog_vbox2;
  GtkWidget *label3;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbuttonbox2;
  GtkWidget *button2;
  GtkWidget *alignment3;
  GtkWidget *hbox9;
  GtkWidget *image3;
  GtkWidget *label5;
  GtkWidget *button3;
  GtkWidget *alignment2;
  GtkWidget *hbox8;
  GtkWidget *image2;
  GtkWidget *label4;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  user2_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (user2_dbox), _("Title2"));
  gtk_window_set_modal (GTK_WINDOW (user2_dbox), TRUE);

  dialog_vbox2 = GTK_DIALOG (user2_dbox)->vbox;
  gtk_widget_show (dialog_vbox2);

  label3 = gtk_label_new (_("Message."));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label3), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 5);

  dialog_action_area2 = GTK_DIALOG (user2_dbox)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_container_add (GTK_CONTAINER (dialog_action_area2), hbuttonbox2);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 30);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button2), alignment3);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox9);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox9), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("b2"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox9), label5, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button3, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button3), alignment2);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox8);

  image2 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox8), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("b1"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox8), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (user2_ok_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (user1_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (user2_dbox, user2_dbox, "user2_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (user2_dbox, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (user2_dbox, label3, "label3");
  GLADE_HOOKUP_OBJECT_NO_REF (user2_dbox, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (user2_dbox, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (user2_dbox, button2, "button2");
  GLADE_HOOKUP_OBJECT (user2_dbox, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (user2_dbox, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (user2_dbox, image3, "image3");
  GLADE_HOOKUP_OBJECT (user2_dbox, label5, "label5");
  GLADE_HOOKUP_OBJECT (user2_dbox, button3, "button3");
  GLADE_HOOKUP_OBJECT (user2_dbox, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (user2_dbox, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (user2_dbox, image2, "image2");
  GLADE_HOOKUP_OBJECT (user2_dbox, label4, "label4");

  gtk_window_add_accel_group (GTK_WINDOW (user2_dbox), accel_group);

  return user2_dbox;
}

GtkWidget*
create_user3_dbox (void)
{
  GtkWidget *user3_dbox;
  GtkWidget *dialog_vbox3;
  GtkWidget *label6;
  GtkWidget *dialog_action_area3;
  GtkWidget *hbuttonbox3;
  GtkWidget *button4;
  GtkWidget *alignment5;
  GtkWidget *hbox11;
  GtkWidget *image5;
  GtkWidget *label9;
  GtkWidget *button5;
  GtkWidget *alignment4;
  GtkWidget *hbox10;
  GtkWidget *image4;
  GtkWidget *label8;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox12;
  GtkWidget *image6;
  GtkWidget *label7;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  user3_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (user3_dbox), _("Title3"));
  gtk_window_set_modal (GTK_WINDOW (user3_dbox), TRUE);

  dialog_vbox3 = GTK_DIALOG (user3_dbox)->vbox;
  gtk_widget_show (dialog_vbox3);

  label6 = gtk_label_new (_("Message."));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label6), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 5);

  dialog_action_area3 = GTK_DIALOG (user3_dbox)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_container_add (GTK_CONTAINER (dialog_action_area3), hbuttonbox3);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox3), 30);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button4, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button4), alignment5);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox11);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox11), image5, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("b3"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox11), label9, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button5);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button5), alignment4);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox10);

  image4 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox10), image4, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("b2"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox10), label8, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button6, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox12);

  image6 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox12), image6, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("b1"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox12), label7, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (user3_ok_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (user2_ok_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (user1_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (user3_dbox, user3_dbox, "user3_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (user3_dbox, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (user3_dbox, label6, "label6");
  GLADE_HOOKUP_OBJECT_NO_REF (user3_dbox, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (user3_dbox, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (user3_dbox, button4, "button4");
  GLADE_HOOKUP_OBJECT (user3_dbox, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (user3_dbox, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (user3_dbox, image5, "image5");
  GLADE_HOOKUP_OBJECT (user3_dbox, label9, "label9");
  GLADE_HOOKUP_OBJECT (user3_dbox, button5, "button5");
  GLADE_HOOKUP_OBJECT (user3_dbox, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (user3_dbox, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (user3_dbox, image4, "image4");
  GLADE_HOOKUP_OBJECT (user3_dbox, label8, "label8");
  GLADE_HOOKUP_OBJECT (user3_dbox, button6, "button6");
  GLADE_HOOKUP_OBJECT (user3_dbox, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (user3_dbox, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (user3_dbox, image6, "image6");
  GLADE_HOOKUP_OBJECT (user3_dbox, label7, "label7");

  gtk_window_add_accel_group (GTK_WINDOW (user3_dbox), accel_group);

  return user3_dbox;
}

