/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "about_cb.h"
#include "about_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_about_dbox (void)
{
  GtkWidget *about_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *notebook1;
  GtkWidget *pixmap2;
  GtkWidget *label2;
  GtkWidget *vbox1;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *label3;
  GtkWidget *scrolledwindow1;
  GtkWidget *text1;
  GtkWidget *label4;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  about_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (about_dbox), _("About GtkTiEmu..."));

  dialog_vbox1 = GTK_DIALOG (about_dbox)->vbox;
  gtk_widget_show (dialog_vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), notebook1, TRUE, TRUE, 0);

  pixmap2 = create_pixmap (about_dbox, "logo.xpm");
  gtk_widget_show (pixmap2);
  gtk_container_add (GTK_CONTAINER (notebook1), pixmap2);

  label2 = gtk_label_new_with_mnemonic (_("_Logo"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 2);

  label5 = gtk_label_new (_("* GtkTiEmu, version 1.45"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox1), label5, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 10, 0);

  label6 = gtk_label_new ("");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox1), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 10, 0);

  label7 = gtk_label_new (_("* Supported platforms are:\n  - Linux (any): RL <roms@tilp.info>\n  - Win32 (Windows 9x/Me/NT4/2000): RL <roms@tilp.info>"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (vbox1), label7, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label7), 10, 0);

  label8 = gtk_label_new_with_mnemonic (_("* Official homepage: http://lpg.ticalc.org/prj__tiemu"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox1), label8, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label8), 10, 0);

  label9 = gtk_label_new (_("* This program is based on UAE (Universal Amiga Emulator)"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox1), label9, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label9), 10, 0);

  label10 = gtk_label_new (_("* Logo by Laminoir"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (vbox1), label10, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label10), 10, 0);

  label12 = gtk_label_new (_("* GUI generated by Glade (RAD)"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (vbox1), label12, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label12), 10, 0);

  label11 = gtk_label_new (_("Program placed under GPL license. Libraries placed under LPGL."));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (vbox1), label11, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label11), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label11), 10, 0);

  label3 = gtk_label_new_with_mnemonic (_("_About"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label3);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow1), 7);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  text1 = gtk_text_view_new ();
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), text1);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (text1), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (text1), GTK_WRAP_WORD);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text1)),
	_("Cannot find the license file."), -1);

  label4 = gtk_label_new_with_mnemonic (_("Li_cense"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label4);

  dialog_action_area1 = GTK_DIALOG (about_dbox)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area1), hbuttonbox1);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  button1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (about_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_dbox, about_dbox, "about_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (about_dbox, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (about_dbox, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (about_dbox, pixmap2, "pixmap2");
  GLADE_HOOKUP_OBJECT (about_dbox, label2, "label2");
  GLADE_HOOKUP_OBJECT (about_dbox, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (about_dbox, label5, "label5");
  GLADE_HOOKUP_OBJECT (about_dbox, label6, "label6");
  GLADE_HOOKUP_OBJECT (about_dbox, label7, "label7");
  GLADE_HOOKUP_OBJECT (about_dbox, label8, "label8");
  GLADE_HOOKUP_OBJECT (about_dbox, label9, "label9");
  GLADE_HOOKUP_OBJECT (about_dbox, label10, "label10");
  GLADE_HOOKUP_OBJECT (about_dbox, label12, "label12");
  GLADE_HOOKUP_OBJECT (about_dbox, label11, "label11");
  GLADE_HOOKUP_OBJECT (about_dbox, label3, "label3");
  GLADE_HOOKUP_OBJECT (about_dbox, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (about_dbox, text1, "text1");
  GLADE_HOOKUP_OBJECT (about_dbox, label4, "label4");
  GLADE_HOOKUP_OBJECT_NO_REF (about_dbox, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (about_dbox, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (about_dbox, button1, "button1");

  gtk_window_add_accel_group (GTK_WINDOW (about_dbox), accel_group);

  return about_dbox;
}

