/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "dbkpt_cb.h"
#include "dbkpt_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_data_bkpts_dbox (void)
{
  GtkWidget *data_bkpts_dbox;
  GtkWidget *vbox30;
  GtkWidget *frame1;
  GtkWidget *scrolledwindow6;
  GtkWidget *clist4;
  GtkWidget *label46;
  GtkWidget *hbox10;
  GtkWidget *hbuttonbox12;
  GtkWidget *button37;
  GtkWidget *button38;
  GtkWidget *button39;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  data_bkpts_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (data_bkpts_dbox), _("Data breakpoints"));

  vbox30 = GTK_DIALOG (data_bkpts_dbox)->vbox;
  gtk_widget_show (vbox30);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox30), frame1, TRUE, TRUE, 0);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (frame1), scrolledwindow6);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow6, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_SHADOW_IN);

  clist4 = gtk_tree_view_new ();
  gtk_widget_show (clist4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), clist4);

  label46 = gtk_label_new (_("Active breakpoints"));
  gtk_widget_show (label46);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label46);
  gtk_label_set_justify (GTK_LABEL (label46), GTK_JUSTIFY_LEFT);

  hbox10 = GTK_DIALOG (data_bkpts_dbox)->action_area;
  gtk_widget_show (hbox10);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbox10), GTK_BUTTONBOX_END);

  hbuttonbox12 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox12);
  gtk_container_add (GTK_CONTAINER (hbox10), hbuttonbox12);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox12), 30);

  button37 = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_show (button37);
  gtk_container_add (GTK_CONTAINER (hbuttonbox12), button37);
  GTK_WIDGET_SET_FLAGS (button37, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button37, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  button38 = gtk_button_new_from_stock ("gtk-delete");
  gtk_widget_show (button38);
  gtk_container_add (GTK_CONTAINER (hbuttonbox12), button38);
  GTK_WIDGET_SET_FLAGS (button38, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button38, "clicked", accel_group,
                              GDK_Delete, 0,
                              GTK_ACCEL_VISIBLE);

  button39 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button39);
  gtk_container_add (GTK_CONTAINER (hbuttonbox12), button39);
  GTK_WIDGET_SET_FLAGS (button39, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button39, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) data_bkpts_dbox, "destroy",
                    G_CALLBACK (on_data_bkpts_dbox_destroy),
                    NULL);
  g_signal_connect ((gpointer) button37, "clicked",
                    G_CALLBACK (on_button_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) button38, "clicked",
                    G_CALLBACK (on_button_del_clicked),
                    NULL);
  g_signal_connect ((gpointer) button39, "clicked",
                    G_CALLBACK (on_button_ok39_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (data_bkpts_dbox, data_bkpts_dbox, "data_bkpts_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (data_bkpts_dbox, vbox30, "vbox30");
  GLADE_HOOKUP_OBJECT (data_bkpts_dbox, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (data_bkpts_dbox, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (data_bkpts_dbox, clist4, "clist4");
  GLADE_HOOKUP_OBJECT (data_bkpts_dbox, label46, "label46");
  GLADE_HOOKUP_OBJECT_NO_REF (data_bkpts_dbox, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (data_bkpts_dbox, hbuttonbox12, "hbuttonbox12");
  GLADE_HOOKUP_OBJECT (data_bkpts_dbox, button37, "button37");
  GLADE_HOOKUP_OBJECT (data_bkpts_dbox, button38, "button38");
  GLADE_HOOKUP_OBJECT (data_bkpts_dbox, button39, "button39");

  gtk_window_add_accel_group (GTK_WINDOW (data_bkpts_dbox), accel_group);

  return data_bkpts_dbox;
}

