/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_debugger_dbox (void);
GtkWidget* create_code_popup_menu (void);
GtkWidget* create_memory_popup_menu (void);
GtkWidget* create_gotocode_dbox (void);
GtkWidget* create_gotodata_dbox (void);
