/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "infos_cb.h"
#include "infos_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_infos_dbox (void)
{
  GtkWidget *infos_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox2;
  GtkWidget *vbox3;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label33;
  GtkWidget *hseparator1;
  GtkWidget *vbox4;
  GtkWidget *label4;
  GtkWidget *label9;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button4;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  infos_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (infos_dbox), _("About TiEmu"));

  dialog_vbox1 = GTK_DIALOG (infos_dbox)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 5);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), vbox3, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("TiEmu, version 1.99"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox3), label1, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  label2 = gtk_label_new (_("The TI emulator for Linux & Windows"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox3), label2, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  label3 = gtk_label_new (_("Taken from xtiger of Jonas Minsberg\nBased on UAE (Universal Amiga Emulator)"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox3), label3, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 0);

  label33 = gtk_label_new (_("Written by roms <roms@tilp.info> \nand tom <corvazier@yahoo.com>"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (vbox3), label33, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label33), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label33), 5, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator1, TRUE, TRUE, 6);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox2), vbox4, TRUE, TRUE, 0);

  label4 = gtk_label_new (_("Current emulation type:"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox4), label4, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label9 = gtk_label_new (_("Calculator type: TI92"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox4), label9, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label9), 5, 0);

  label5 = gtk_label_new (_("ROM version: version 1.11"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox4), label5, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 5, 0);

  label6 = gtk_label_new (_("Emulated RAM: 128 Kb"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox4), label6, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 0);

  label7 = gtk_label_new (_("Main ROM size: 1 Mb"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (vbox4), label7, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label7), 5, 0);

  label8 = gtk_label_new (_("Flash ROM: yes/no"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox4), label8, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label8), 5, 0);

  dialog_action_area1 = GTK_DIALOG (infos_dbox)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area1), hbuttonbox1);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  button4 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button4, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button4, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) infos_dbox, "destroy",
                    G_CALLBACK (on_infos_dbox_destroy),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (infos_dbox, infos_dbox, "infos_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (infos_dbox, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (infos_dbox, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (infos_dbox, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (infos_dbox, label1, "label1");
  GLADE_HOOKUP_OBJECT (infos_dbox, label2, "label2");
  GLADE_HOOKUP_OBJECT (infos_dbox, label3, "label3");
  GLADE_HOOKUP_OBJECT (infos_dbox, label33, "label33");
  GLADE_HOOKUP_OBJECT (infos_dbox, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (infos_dbox, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (infos_dbox, label4, "label4");
  GLADE_HOOKUP_OBJECT (infos_dbox, label9, "label9");
  GLADE_HOOKUP_OBJECT (infos_dbox, label5, "label5");
  GLADE_HOOKUP_OBJECT (infos_dbox, label6, "label6");
  GLADE_HOOKUP_OBJECT (infos_dbox, label7, "label7");
  GLADE_HOOKUP_OBJECT (infos_dbox, label8, "label8");
  GLADE_HOOKUP_OBJECT_NO_REF (infos_dbox, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (infos_dbox, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (infos_dbox, button4, "button4");

  gtk_window_add_accel_group (GTK_WINDOW (infos_dbox), accel_group);

  return infos_dbox;
}

