/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "pgmentbkpt_cb.h"
#include "pgmentbkpt_dbox.h"
#include "support.h"

GtkWidget*
create_pgmentrybkpt_dbox (void)
{
  GtkWidget *pgmentrybkpt_dbox;
  GtkWidget *vbox22;
  GtkWidget *vbox23;
  GtkWidget *label23;
  GtkWidget *vbox24;
  GtkWidget *list3;
  GtkWidget *hbox4;
  GtkWidget *hbuttonbox5;
  GtkWidget *button21;
  GtkWidget *hbox5;
  GtkWidget *pixmap1;
  guint label24_key;
  GtkWidget *label24;
  GtkWidget *button22;
  GtkWidget *hbox6;
  GtkWidget *pixmap2;
  guint label25_key;
  GtkWidget *label25;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  pgmentrybkpt_dbox = gtk_dialog_new ();
  gtk_widget_set_name (pgmentrybkpt_dbox, "pgmentrybkpt_dbox");
  gtk_object_set_data (GTK_OBJECT (pgmentrybkpt_dbox), "pgmentrybkpt_dbox", pgmentrybkpt_dbox);
  gtk_window_set_title (GTK_WINDOW (pgmentrybkpt_dbox), _("Program entry breakpoint"));

  vbox22 = GTK_DIALOG (pgmentrybkpt_dbox)->vbox;
  gtk_widget_set_name (vbox22, "vbox22");
  gtk_object_set_data (GTK_OBJECT (pgmentrybkpt_dbox), "vbox22", vbox22);
  gtk_widget_show (vbox22);

  vbox23 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox23, "vbox23");
  gtk_widget_ref (vbox23);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "vbox23", vbox23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox23);
  gtk_box_pack_start (GTK_BOX (vbox22), vbox23, TRUE, TRUE, 0);

  label23 = gtk_label_new (_("Select program in which \nto set breakpoint"));
  gtk_widget_set_name (label23, "label23");
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (vbox23), label23, FALSE, FALSE, 3);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label23), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label23), 10, 0);

  vbox24 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox24, "vbox24");
  gtk_widget_ref (vbox24);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "vbox24", vbox24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox24);
  gtk_box_pack_start (GTK_BOX (vbox23), vbox24, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox24), 7);

  list3 = gtk_list_new ();
  gtk_widget_set_name (list3, "list3");
  gtk_widget_ref (list3);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "list3", list3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (list3);
  gtk_box_pack_start (GTK_BOX (vbox24), list3, TRUE, TRUE, 0);
  gtk_widget_set_usize (list3, 100, 200);

  hbox4 = GTK_DIALOG (pgmentrybkpt_dbox)->action_area;
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_object_set_data (GTK_OBJECT (pgmentrybkpt_dbox), "hbox4", hbox4);
  gtk_widget_show (hbox4);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 10);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox5, "hbuttonbox5");
  gtk_widget_ref (hbuttonbox5);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "hbuttonbox5", hbuttonbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (hbox4), hbuttonbox5, TRUE, TRUE, 0);

  button21 = gtk_button_new ();
  gtk_widget_set_name (button21, "button21");
  gtk_widget_ref (button21);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "button21", button21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button21);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button21);
  GTK_WIDGET_SET_FLAGS (button21, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button21, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox5 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (button21), hbox5);

  pixmap1 = create_pixmap (pgmentrybkpt_dbox, "yes.xpm");
  gtk_widget_set_name (pixmap1, "pixmap1");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox5), pixmap1, TRUE, FALSE, 0);

  label24 = gtk_label_new ("");
  label24_key = gtk_label_parse_uline (GTK_LABEL (label24),
                                   _("_OK"));
  gtk_widget_set_name (label24, "label24");
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label24), 5, 0);

  button22 = gtk_button_new ();
  gtk_widget_set_name (button22, "button22");
  gtk_widget_ref (button22);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "button22", button22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button22);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button22);
  GTK_WIDGET_SET_FLAGS (button22, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button22, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (button22), hbox6);

  pixmap2 = create_pixmap (pgmentrybkpt_dbox, "no.xpm");
  gtk_widget_set_name (pixmap2, "pixmap2");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox6), pixmap2, TRUE, FALSE, 0);

  label25 = gtk_label_new ("");
  label25_key = gtk_label_parse_uline (GTK_LABEL (label25),
                                   _("_Cancel"));
  gtk_widget_set_name (label25, "label25");
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (pgmentrybkpt_dbox), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox6), label25, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label25), 5, 0);

  gtk_signal_connect (GTK_OBJECT (pgmentrybkpt_dbox), "destroy",
                      GTK_SIGNAL_FUNC (on_pgmentrybkpt_dbox_destroy),
                      pgmentrybkpt_dbox);
  gtk_signal_connect (GTK_OBJECT (button21), "clicked",
                      GTK_SIGNAL_FUNC (on_button21_clicked),
                      pgmentrybkpt_dbox);
  gtk_signal_connect (GTK_OBJECT (button22), "clicked",
                      GTK_SIGNAL_FUNC (on_button22_enter),
                      pgmentrybkpt_dbox);

  gtk_widget_add_accelerator (button21, "clicked", accel_group,
                              label24_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (button22, "clicked", accel_group,
                              label25_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (pgmentrybkpt_dbox), accel_group);

  return pgmentrybkpt_dbox;
}

