/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "scopt_cb.h"
#include "scopt_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_scopt_dbox (void)
{
  GtkWidget *scopt_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *frame2;
  GtkWidget *hbox3;
  GtkWidget *vbox3;
  GtkWidget *radiobutton22;
  GSList *radiobutton22_group = NULL;
  GtkWidget *radiobutton23;
  GtkWidget *hseparator1;
  GtkWidget *radiobutton24;
  GSList *radiobutton24_group = NULL;
  GtkWidget *radiobutton25;
  GtkWidget *label3;
  GtkWidget *frame4;
  GtkWidget *entry1;
  GtkWidget *label4;
  GtkWidget *frame3;
  GtkWidget *vbox2;
  GtkWidget *radiobutton18;
  GSList *radiobutton18_group = NULL;
  GtkWidget *radiobutton19;
  GtkWidget *radiobutton20;
  GtkWidget *radiobutton21;
  GtkWidget *label5;
  GtkWidget *frame5;
  GtkWidget *label3;
  GtkWidget *label6;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *cancel_button;
  GtkWidget *ok_button;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  scopt_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (scopt_dbox), _("Screen capture options"));

  dialog_vbox1 = GTK_DIALOG (scopt_dbox)->vbox;
  gtk_widget_show (dialog_vbox1);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, TRUE, TRUE, 0);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_table_attach (GTK_TABLE (table1), frame2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (frame2), hbox3);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 5);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox3, TRUE, TRUE, 0);

  radiobutton22 = gtk_radio_button_new_with_mnemonic (NULL, _("Black&White"));
  gtk_widget_show (radiobutton22);
  gtk_box_pack_start (GTK_BOX (vbox3), radiobutton22, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton22), radiobutton22_group);
  radiobutton22_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton22));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton22), TRUE);

  radiobutton23 = gtk_radio_button_new_with_mnemonic (NULL, _("Color"));
  gtk_widget_show (radiobutton23);
  gtk_box_pack_start (GTK_BOX (vbox3), radiobutton23, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton23), radiobutton22_group);
  radiobutton22_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton23));

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox3), hseparator1, TRUE, TRUE, 0);

  radiobutton24 = gtk_radio_button_new_with_mnemonic (NULL, _("LCD only"));
  gtk_widget_show (radiobutton24);
  gtk_box_pack_start (GTK_BOX (vbox3), radiobutton24, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton24), radiobutton24_group);
  radiobutton24_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton24));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton24), TRUE);

  radiobutton25 = gtk_radio_button_new_with_mnemonic (NULL, _("Calculator"));
  gtk_widget_show (radiobutton25);
  gtk_box_pack_start (GTK_BOX (vbox3), radiobutton25, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton25), radiobutton24_group);
  radiobutton24_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton25));

  label3 = gtk_label_new (_("Image type:"));
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label3);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_table_attach (GTK_TABLE (table1), frame4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 5);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_container_add (GTK_CONTAINER (frame4), entry1);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("screenshot"));

  label4 = gtk_label_new (_("Pattern:"));
  gtk_widget_show (label4);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_table_attach (GTK_TABLE (table1), frame3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 5);

  vbox2 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame3), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 5);

  radiobutton18 = gtk_radio_button_new_with_mnemonic (NULL, _("PCX (RLE compressed)"));
  gtk_widget_show (radiobutton18);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton18, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton18), radiobutton18_group);
  radiobutton18_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton18));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton18), TRUE);

  radiobutton19 = gtk_radio_button_new_with_mnemonic (NULL, _("XPM (Unix format)"));
  gtk_widget_show (radiobutton19);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton19, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton19), radiobutton18_group);
  radiobutton18_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton19));

  radiobutton20 = gtk_radio_button_new_with_mnemonic (NULL, _("JPEG"));
  gtk_widget_show (radiobutton20);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton20, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton20), radiobutton18_group);
  radiobutton18_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton20));

  radiobutton21 = gtk_radio_button_new_with_mnemonic (NULL, _("BMP (not compressed)"));
  gtk_widget_show (radiobutton21);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton21, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton21), radiobutton18_group);
  radiobutton18_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton21));

  label5 = gtk_label_new (_("Image format:"));
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label5);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_table_attach (GTK_TABLE (table1), frame5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame5), 5);

  label3 = gtk_label_new (_("screenshot000.pcx"));
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (frame5), label3);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 10, 0);

  label6 = gtk_label_new (_("Resulting filename:"));
  gtk_widget_show (label6);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label6);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);

  dialog_action_area1 = GTK_DIALOG (scopt_dbox)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area1), hbuttonbox1);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  cancel_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cancel_button);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), ok_button);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) scopt_dbox, "destroy",
                    G_CALLBACK (on_scopt_dbox_destroy),
                    NULL);
  g_signal_connect ((gpointer) radiobutton22, "toggled",
                    G_CALLBACK (on_scopt_radiobutton22_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton23, "toggled",
                    G_CALLBACK (on_scopt_radiobutton23_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton24, "toggled",
                    G_CALLBACK (on_scopt_radiobutton24_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton25, "toggled",
                    G_CALLBACK (on_scopt_radiobutton25_toggled),
                    NULL);
  g_signal_connect ((gpointer) entry1, "changed",
                    G_CALLBACK (on_entry1_changed),
                    NULL);
  g_signal_connect ((gpointer) radiobutton18, "toggled",
                    G_CALLBACK (on_scopt_radiobutton18_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton19, "toggled",
                    G_CALLBACK (on_scopt_radiobutton19_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton20, "toggled",
                    G_CALLBACK (on_scopt_radiobutton20_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton21, "toggled",
                    G_CALLBACK (on_scopt_radiobutton21_toggled),
                    NULL);
  g_signal_connect ((gpointer) cancel_button, "clicked",
                    G_CALLBACK (on_scopt_cancel_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) ok_button, "clicked",
                    G_CALLBACK (on_scopt_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (scopt_dbox, scopt_dbox, "scopt_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (scopt_dbox, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (scopt_dbox, table1, "table1");
  GLADE_HOOKUP_OBJECT (scopt_dbox, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (scopt_dbox, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (scopt_dbox, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (scopt_dbox, radiobutton22, "radiobutton22");
  GLADE_HOOKUP_OBJECT (scopt_dbox, radiobutton23, "radiobutton23");
  GLADE_HOOKUP_OBJECT (scopt_dbox, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (scopt_dbox, radiobutton24, "radiobutton24");
  GLADE_HOOKUP_OBJECT (scopt_dbox, radiobutton25, "radiobutton25");
  GLADE_HOOKUP_OBJECT (scopt_dbox, label3, "label3");
  GLADE_HOOKUP_OBJECT (scopt_dbox, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (scopt_dbox, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (scopt_dbox, label4, "label4");
  GLADE_HOOKUP_OBJECT (scopt_dbox, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (scopt_dbox, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (scopt_dbox, radiobutton18, "radiobutton18");
  GLADE_HOOKUP_OBJECT (scopt_dbox, radiobutton19, "radiobutton19");
  GLADE_HOOKUP_OBJECT (scopt_dbox, radiobutton20, "radiobutton20");
  GLADE_HOOKUP_OBJECT (scopt_dbox, radiobutton21, "radiobutton21");
  GLADE_HOOKUP_OBJECT (scopt_dbox, label5, "label5");
  GLADE_HOOKUP_OBJECT (scopt_dbox, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (scopt_dbox, label3, "label3");
  GLADE_HOOKUP_OBJECT (scopt_dbox, label6, "label6");
  GLADE_HOOKUP_OBJECT_NO_REF (scopt_dbox, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (scopt_dbox, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (scopt_dbox, cancel_button, "cancel_button");
  GLADE_HOOKUP_OBJECT (scopt_dbox, ok_button, "ok_button");

  gtk_window_add_accel_group (GTK_WINDOW (scopt_dbox), accel_group);

  return scopt_dbox;
}

