/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "startup_cb.h"
#include "startup_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_startup_dbox (void)
{
  GtkWidget *startup_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *label2;
  GtkWidget *scrolledwindow1;
  GtkWidget *text1;
  GtkWidget *label3;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  startup_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (startup_dbox), _("Welcome to TiEmu !"));
  gtk_window_set_modal (GTK_WINDOW (startup_dbox), TRUE);

  dialog_vbox1 = GTK_DIALOG (startup_dbox)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("This box appears only once or whenever a new\nversion is installed.\nYou will find in the box below some news about\nTiEmu (the ChangeLog file):"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox1), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label2), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow1), 7);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  text1 = gtk_text_view_new ();
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), text1);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (text1), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (text1), GTK_WRAP_WORD);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text1)),
	_("Cannot find the CHANGELOG file."), -1);

  label3 = gtk_label_new (_("Latest version of TiEmu can  be found at:\n<http://lpg.ticalc.org/prj_tiemu>\nPlease report any bugs at: <roms@tilp.info>\nMailing list: <tilp-devel@lists.sf.net>"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox1), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label3), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 0);

  dialog_action_area1 = GTK_DIALOG (startup_dbox)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area1), hbuttonbox1);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  button1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) startup_dbox, "show",
                    G_CALLBACK (on_startup_dbox_show),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (startup_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (startup_dbox, startup_dbox, "startup_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (startup_dbox, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (startup_dbox, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (startup_dbox, label2, "label2");
  GLADE_HOOKUP_OBJECT (startup_dbox, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (startup_dbox, text1, "text1");
  GLADE_HOOKUP_OBJECT (startup_dbox, label3, "label3");
  GLADE_HOOKUP_OBJECT_NO_REF (startup_dbox, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (startup_dbox, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (startup_dbox, button1, "button1");

  gtk_window_add_accel_group (GTK_WINDOW (startup_dbox), accel_group);

  return startup_dbox;
}

