/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "viewlog_cb.h"
#include "viewlog_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_viewlog_dbox (void)
{
  GtkWidget *viewlog_dbox;
  GtkWidget *vbox19;
  GtkWidget *vbox20;
  GtkWidget *label22;
  GtkWidget *vbox21;
  GtkWidget *list2;
  GtkWidget *hbox3;
  GtkWidget *hbuttonbox4;
  GtkWidget *button16;
  GtkWidget *alignment1;
  GtkWidget *hbox4;
  GtkWidget *image1;
  GtkWidget *label23;
  GtkWidget *button17;
  GtkWidget *button18;
  GtkWidget *button19;
  GtkWidget *alignment2;
  GtkWidget *hbox5;
  GtkWidget *image2;
  GtkWidget *label24;
  GtkWidget *button20;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  viewlog_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (viewlog_dbox), _("View log"));

  vbox19 = GTK_DIALOG (viewlog_dbox)->vbox;
  gtk_widget_show (vbox19);

  vbox20 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox20);
  gtk_box_pack_start (GTK_BOX (vbox19), vbox20, TRUE, TRUE, 0);

  label22 = gtk_label_new (_("Select new ROM version:"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (vbox20), label22, FALSE, FALSE, 3);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label22), 10, 0);

  vbox21 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox21);
  gtk_box_pack_start (GTK_BOX (vbox20), vbox21, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox21), 7);

  list2 = gtk_tree_view_new ();
  gtk_widget_show (list2);
  gtk_box_pack_start (GTK_BOX (vbox21), list2, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (list2, GTK_CAN_FOCUS);

  hbox3 = GTK_DIALOG (viewlog_dbox)->action_area;
  gtk_widget_show (hbox3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbox3), GTK_BUTTONBOX_END);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_container_add (GTK_CONTAINER (hbox3), hbuttonbox4);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button16), alignment1);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox4);

  image1 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox4), image1, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox4), label23, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);

  button17 = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  button18 = gtk_button_new_from_stock ("gtk-clear");
  gtk_widget_show (button18);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button18);
  GTK_WIDGET_SET_FLAGS (button18, GTK_CAN_DEFAULT);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button19);
  GTK_WIDGET_SET_FLAGS (button19, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button19), alignment2);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox5);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox5), image2, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("_Start"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);

  button20 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button20);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button20);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button20, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) viewlog_dbox, "destroy",
                    G_CALLBACK (on_viewlog_dbox_destroy),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (viewlog_dbox, viewlog_dbox, "viewlog_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (viewlog_dbox, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, vbox20, "vbox20");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, label22, "label22");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, vbox21, "vbox21");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, list2, "list2");
  GLADE_HOOKUP_OBJECT_NO_REF (viewlog_dbox, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, button16, "button16");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, image1, "image1");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, label23, "label23");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, button17, "button17");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, button18, "button18");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, button19, "button19");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, image2, "image2");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, label24, "label24");
  GLADE_HOOKUP_OBJECT (viewlog_dbox, button20, "button20");

  gtk_window_add_accel_group (GTK_WINDOW (viewlog_dbox), accel_group);

  return viewlog_dbox;
}

