/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_flash_fileselection (void);
GtkWidget* create_romfile_fileselection (void);
GtkWidget* create_step1_dbox (void);
GtkWidget* create_msg1_dbox (void);
GtkWidget* create_step3_dbox (void);
GtkWidget* create_wait_dbox (void);
