/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <stdio.h>
#ifndef __WIN32__
#include <unistd.h>
#endif

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "boxes_cb.h"
#include "boxes_intf.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_list_keys_dialog (void)
{
  GtkWidget *scrolledwindow2;
  GtkWidget *list_keys;

  list_keys_dialog = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (list_keys_dialog), _("Keys"));
  gtk_window_set_default_size (GTK_WINDOW (list_keys_dialog), 100, 200);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (list_keys_dialog), scrolledwindow2);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow2, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  list_keys = gtk_tree_view_new ();
  gtk_widget_show (list_keys);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), list_keys);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (list_keys), FALSE);

  g_signal_connect ((gpointer) list_keys_dialog, "delete_event",
                    G_CALLBACK (on_list_keys_dialog_delete_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) list_keys_dialog, "destroy_event",
                    G_CALLBACK (on_list_keys_dialog_delete_destroy_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (list_keys_dialog, list_keys_dialog, "list_keys_dialog");
  GLADE_HOOKUP_OBJECT (list_keys_dialog, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (list_keys_dialog, list_keys, "list_keys");

  return list_keys_dialog;
}

GtkWidget*
create_skin_changed (gpointer action)
{
  GtkWidget *skin_changed;
  GtkWidget *vbox5;
  GtkWidget *label8;
  GtkWidget *hbox5;
  GtkWidget *hbuttonbox3;
  GtkWidget *skin_changed_save;
  GtkWidget *alignment5;
  GtkWidget *hbox10;
  GtkWidget *image5;
  GtkWidget *label14;
  GtkWidget *skin_changed_ignore;
  GtkWidget *alignment3;
  GtkWidget *hbox8;
  GtkWidget *image3;
  GtkWidget *label12;
  GtkWidget *skin_changed_cancel;
  GtkWidget *alignment6;
  GtkWidget *hbox11;
  GtkWidget *image6;
  GtkWidget *label15;

  skin_changed = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (skin_changed), _("Save changes ?"));
  gtk_window_set_modal (GTK_WINDOW (skin_changed), TRUE);

  vbox5 = GTK_DIALOG (skin_changed)->vbox;
  gtk_widget_show (vbox5);

  label8 = gtk_label_new (_("The current skin has changed.\nDo you want to save your modifications ?"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox5), label8, TRUE, FALSE, 10);

  hbox5 = GTK_DIALOG (skin_changed)->action_area;
  gtk_widget_show (hbox5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbox5), GTK_BUTTONBOX_END);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_container_add (GTK_CONTAINER (hbox5), hbuttonbox3);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox3), 30);

  skin_changed_save = gtk_button_new ();
  gtk_widget_show (skin_changed_save);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), skin_changed_save);
  GTK_WIDGET_SET_FLAGS (skin_changed_save, GTK_CAN_DEFAULT);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (skin_changed_save), alignment5);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox10);

  image5 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox10), image5, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Save"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox10), label14, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);

  skin_changed_ignore = gtk_button_new ();
  gtk_widget_show (skin_changed_ignore);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), skin_changed_ignore);
  GTK_WIDGET_SET_FLAGS (skin_changed_ignore, GTK_CAN_DEFAULT);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (skin_changed_ignore), alignment3);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox8);

  image3 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox8), image3, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Discard"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox8), label12, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);

  skin_changed_cancel = gtk_button_new ();
  gtk_widget_show (skin_changed_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), skin_changed_cancel);
  GTK_WIDGET_SET_FLAGS (skin_changed_cancel, GTK_CAN_DEFAULT);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (skin_changed_cancel), alignment6);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox11);

  image6 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox11), image6, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox11), label15, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) skin_changed, "delete_event",
                    G_CALLBACK (on_skin_changed_delete_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) skin_changed, "destroy_event",
                    G_CALLBACK (on_skin_changed_delete_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) skin_changed_save, "clicked",
		    G_CALLBACK (on_skin_changed_save_clicked),
		    action);
  g_signal_connect ((gpointer) skin_changed_ignore, "clicked",
		    G_CALLBACK (on_skin_changed_ignore_clicked),
		    action);
  g_signal_connect ((gpointer) skin_changed_cancel, "clicked",
		    G_CALLBACK (on_skin_changed_cancel_clicked),
		    action);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (skin_changed, skin_changed, "skin_changed");
  GLADE_HOOKUP_OBJECT_NO_REF (skin_changed, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (skin_changed, label8, "label8");
  GLADE_HOOKUP_OBJECT_NO_REF (skin_changed, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (skin_changed, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (skin_changed, skin_changed_save, "skin_changed_save");
  GLADE_HOOKUP_OBJECT (skin_changed, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (skin_changed, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (skin_changed, image5, "image5");
  GLADE_HOOKUP_OBJECT (skin_changed, label14, "label14");
  GLADE_HOOKUP_OBJECT (skin_changed, skin_changed_ignore, "skin_changed_ignore");
  GLADE_HOOKUP_OBJECT (skin_changed, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (skin_changed, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (skin_changed, image3, "image3");
  GLADE_HOOKUP_OBJECT (skin_changed, label12, "label12");
  GLADE_HOOKUP_OBJECT (skin_changed, skin_changed_cancel, "skin_changed_cancel");
  GLADE_HOOKUP_OBJECT (skin_changed, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (skin_changed, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (skin_changed, image6, "image6");
  GLADE_HOOKUP_OBJECT (skin_changed, label15, "label15");

  return skin_changed;
}

GtkWidget*
create_about_box (void)
{
  GtkWidget *about_box;
  GtkWidget *dialog_vbox3;
  GtkWidget *frame3;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *dialog_action_area3;
  GtkWidget *about_ok;
  GtkWidget *alignment4;
  GtkWidget *hbox9;
  GtkWidget *image4;
  GtkWidget *label13;

  about_box = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (about_box), _("About... Skinedit"));

  dialog_vbox3 = GTK_DIALOG (about_box)->vbox;
  gtk_widget_show (dialog_vbox3);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), frame3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 5);

  label9 = gtk_label_new (_("Skinedit was written by Julien BLACHE <jb@tilp.info>\n\nThis program is released under the terms of the \nGNU GENERAL PUBLIC LICENSE\nVERSION 2\n\nIt is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the\nimplied warranty of MERCHANTABILITY or FITNESS\nFOR A PARTICULAR PURPOSE. See the GNU\nGeneral Public License for more details."));
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (frame3), label9);
  gtk_misc_set_padding (GTK_MISC (label9), 5, 5);

  label10 = gtk_label_new (_("Skinedit infos"));
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label10);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);

  dialog_action_area3 = GTK_DIALOG (about_box)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  about_ok = gtk_button_new ();
  gtk_widget_show (about_ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (about_box), about_ok, 0);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (about_ok), alignment4);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox9);

  image4 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox9), image4, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("OK !"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox9), label13, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) about_box, "delete_event",
                    G_CALLBACK (on_about_box_delete_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) about_box, "destroy_event",
                    G_CALLBACK (on_about_box_delete_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) about_ok, "clicked",
                    G_CALLBACK (on_about_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_box, about_box, "about_box");
  GLADE_HOOKUP_OBJECT_NO_REF (about_box, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (about_box, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (about_box, label9, "label9");
  GLADE_HOOKUP_OBJECT (about_box, label9, "label9");
  GLADE_HOOKUP_OBJECT_NO_REF (about_box, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (about_box, about_ok, "about_ok");
  GLADE_HOOKUP_OBJECT (about_box, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (about_box, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (about_box, image4, "image4");
  GLADE_HOOKUP_OBJECT (about_box, label13, "label13");

  return about_box;
}

