/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

# include <gtk/gtk.h>	//#include "gtksdl.h"

GtkWidget* create_main_window (void);
GtkWidget* create_filesel (void);

extern GtkWidget *drawingarea1;	// sdl_event
extern GtkWidget *statusbar;

extern GdkPixbuf *pixbuf;

//GtkWidget *area;  // = drawingarea
//GtkSDL *sdl_area; // = pixbuf


// SDL surface = pixbuf
// sdl_are = drawing_area
