/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include "gtksdl.h"

GtkWidget* create_main_window (void);
GtkWidget* create_filesel (void);

GtkWidget *sdl_eventbox;
GtkWidget *statusbar;

GtkWidget *area;
GtkSDL *sdl_area;
