/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "prop_cb.h"
#include "prop_intf.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    g_object_ref (widget), (GDestroyNotify) g_object_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_lcd_color_select (gpointer action)
{
  GtkWidget *lcd_color_select;
  GtkWidget *lcd_color_ok;
  GtkWidget *lcd_color_unused;
  GtkWidget *lcd_color_cancel;
  GtkWidget *colorselection1;

  lcd_color_select = gtk_color_selection_dialog_new (_("Select Color"));
  gtk_container_set_border_width (GTK_CONTAINER (lcd_color_select), 10);
  gtk_window_set_modal (GTK_WINDOW (lcd_color_select), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (lcd_color_select), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (lcd_color_select), GDK_WINDOW_TYPE_HINT_DIALOG);

  lcd_color_ok = GTK_COLOR_SELECTION_DIALOG (lcd_color_select)->ok_button;
  gtk_widget_show (lcd_color_ok);
  GTK_WIDGET_SET_FLAGS (lcd_color_ok, GTK_CAN_DEFAULT);

  lcd_color_unused = GTK_COLOR_SELECTION_DIALOG (lcd_color_select)->cancel_button;
  gtk_widget_show (lcd_color_unused);
  GTK_WIDGET_SET_FLAGS (lcd_color_unused, GTK_CAN_DEFAULT);

  lcd_color_cancel = GTK_COLOR_SELECTION_DIALOG (lcd_color_select)->cancel_button;
  gtk_widget_show (lcd_color_cancel);
  GTK_WIDGET_SET_FLAGS (lcd_color_cancel, GTK_CAN_DEFAULT);

  colorselection1 = GTK_COLOR_SELECTION_DIALOG (lcd_color_select)->colorsel;
  gtk_widget_show (colorselection1);
  gtk_color_selection_set_has_opacity_control (GTK_COLOR_SELECTION (colorselection1), FALSE);
  gtk_color_selection_set_has_palette (GTK_COLOR_SELECTION (colorselection1), TRUE);

  g_signal_connect ((gpointer) lcd_color_select, "delete_event",
                    G_CALLBACK (on_lcd_color_select_delete_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) lcd_color_select, "destroy_event",
                    G_CALLBACK (on_lcd_color_select_delete_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) lcd_color_ok, "clicked",
                    G_CALLBACK (on_lcd_color_ok_clicked),
                    action);
  g_signal_connect ((gpointer) lcd_color_cancel, "clicked",
                    G_CALLBACK (on_lcd_color_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (lcd_color_select, lcd_color_select, "lcd_color_select");
  GLADE_HOOKUP_OBJECT_NO_REF (lcd_color_select, lcd_color_ok, "lcd_color_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (lcd_color_select, lcd_color_unused, "lcd_color_unused");
  GLADE_HOOKUP_OBJECT_NO_REF (lcd_color_select, lcd_color_cancel, "lcd_color_cancel");
  GLADE_HOOKUP_OBJECT_NO_REF (lcd_color_select, colorselection1, "colorselection1");

  return lcd_color_select;
}

GtkWidget*
create_prop_dialog (void)
{
  GtkWidget *prop_dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox2;
  GtkWidget *hbox2;
  GtkWidget *hbox3;
  GtkWidget *table1;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *prop_entry_title;
  GtkWidget *prop_entry_author;
  GtkWidget *hseparator1;
  GtkWidget *hbox4;
  GtkWidget *frame1;
  GtkWidget *table2;
  GSList *ti73_group = NULL;
  GtkWidget *ti73;
  GtkWidget *ti82;
  GtkWidget *ti83;
  GtkWidget *ti83p;
  GtkWidget *ti84p;
  GtkWidget *ti85;
  GtkWidget *ti86;
  GtkWidget *ti89;
  GtkWidget *ti89t;
  GtkWidget *ti92;
  GtkWidget *ti92p;
  GtkWidget *v200;
  GtkWidget *label5;
  GtkWidget *vseparator1;
  GtkWidget *frame2;
  GtkWidget *table3;
  GtkWidget *lcd_high_contrast;
  GSList *lcd_high_contrast_group = NULL;
  GtkWidget *lcd_low_contrast;
  GtkWidget *lcd_custom;
  GtkWidget *lcd_low_white;
  GtkWidget *lcd_hi_white;
  GtkWidget *lcd_hi_black;
  GtkWidget *lcd_low_black;
  GtkWidget *lcd_custom_white;
  GtkWidget *lcd_custom_black;
  GtkWidget *label6;
  GtkWidget *dialog_action_area2;
  GtkWidget *prop_dlg_cancel;
  GtkWidget *prop_dlg_ok;

  prop_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (prop_dialog), _("Properties"));
  gtk_window_set_modal (GTK_WINDOW (prop_dialog), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (prop_dialog), 473, 266);
  gtk_window_set_type_hint (GTK_WINDOW (prop_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (prop_dialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 10);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, TRUE, TRUE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (hbox2), hbox3, TRUE, TRUE, 0);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (hbox3), table1, TRUE, TRUE, 0);

  label3 = gtk_label_new (_("Title : "));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new (_("Author : "));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  prop_entry_title = gtk_entry_new ();
  gtk_widget_show (prop_entry_title);
  gtk_table_attach (GTK_TABLE (table1), prop_entry_title, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  prop_entry_author = gtk_entry_new ();
  gtk_widget_show (prop_entry_author);
  gtk_table_attach (GTK_TABLE (table1), prop_entry_author, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator1, FALSE, TRUE, 4);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox4, FALSE, FALSE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox4), frame1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 3);

  table2 = gtk_table_new (4, 3, TRUE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (frame1), table2);

  ti73 = gtk_radio_button_new_with_mnemonic (NULL, _("TI-73"));
  gtk_widget_show (ti73);
  gtk_table_attach (GTK_TABLE (table2), ti73, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti73), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti73));

  ti82 = gtk_radio_button_new_with_mnemonic (NULL, _("TI-82"));
  gtk_widget_show (ti82);
  gtk_table_attach (GTK_TABLE (table2), ti82, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti82), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti82));

  ti83 = gtk_radio_button_new_with_mnemonic (NULL, _("TI-83"));
  gtk_widget_show (ti83);
  gtk_table_attach (GTK_TABLE (table2), ti83, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti83), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti83));

  ti83p = gtk_radio_button_new_with_mnemonic (NULL, _("TI-83+"));
  gtk_widget_show (ti83p);
  gtk_table_attach (GTK_TABLE (table2), ti83p, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti83p), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti83p));

  ti92 = gtk_radio_button_new_with_mnemonic (NULL, _("TI-92"));
  gtk_widget_show (ti92);
  gtk_table_attach (GTK_TABLE (table2), ti92, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti92), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti92));

  ti92p = gtk_radio_button_new_with_mnemonic (NULL, _("TI-92 Plus"));
  gtk_widget_show (ti92p);
  gtk_table_attach (GTK_TABLE (table2), ti92p, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti92p), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti92p));

  v200 = gtk_radio_button_new_with_mnemonic (NULL, _("Voyage 200"));
  gtk_widget_show (v200);
  gtk_table_attach (GTK_TABLE (table2), v200, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (v200), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (v200));

  ti89 = gtk_radio_button_new_with_mnemonic (NULL, _("TI-89"));
  gtk_widget_show (ti89);
  gtk_table_attach (GTK_TABLE (table2), ti89, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti89), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti89));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (ti89), TRUE);

  ti86 = gtk_radio_button_new_with_mnemonic (NULL, _("TI-86"));
  gtk_widget_show (ti86);
  gtk_table_attach (GTK_TABLE (table2), ti86, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti86), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti86));

  ti85 = gtk_radio_button_new_with_mnemonic (NULL, _("TI-85"));
  gtk_widget_show (ti85);
  gtk_table_attach (GTK_TABLE (table2), ti85, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti85), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti85));

  ti84p = gtk_radio_button_new_with_mnemonic (NULL, _("TI-84+"));
  gtk_widget_show (ti84p);
  gtk_table_attach (GTK_TABLE (table2), ti84p, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti84p), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti84p));

  ti89t = gtk_radio_button_new_with_mnemonic (NULL, _("Titanium"));
  gtk_widget_show (ti89t);
  gtk_table_attach (GTK_TABLE (table2), ti89t, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ti89t), ti73_group);
  ti73_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ti89t));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (ti89t), TRUE);

  label5 = gtk_label_new (_("Calc type"));
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label5);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox4), vseparator1, FALSE, TRUE, 4);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox4), frame2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 3);

  table3 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (frame2), table3);

  lcd_high_contrast = gtk_radio_button_new_with_mnemonic (NULL, _("High contrast"));
  gtk_widget_show (lcd_high_contrast);
  gtk_table_attach (GTK_TABLE (table3), lcd_high_contrast, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (lcd_high_contrast), lcd_high_contrast_group);
  lcd_high_contrast_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (lcd_high_contrast));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (lcd_high_contrast), TRUE);

  lcd_low_contrast = gtk_radio_button_new_with_mnemonic (NULL, _("Low contrast"));
  gtk_widget_show (lcd_low_contrast);
  gtk_table_attach (GTK_TABLE (table3), lcd_low_contrast, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (lcd_low_contrast), lcd_high_contrast_group);
  lcd_high_contrast_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (lcd_low_contrast));

  lcd_custom = gtk_radio_button_new_with_mnemonic (NULL, _("Custom"));
  gtk_widget_show (lcd_custom);
  gtk_table_attach (GTK_TABLE (table3), lcd_custom, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (lcd_custom), lcd_high_contrast_group);
  lcd_high_contrast_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (lcd_custom));

  lcd_low_white = gtk_drawing_area_new ();
  gtk_widget_show (lcd_low_white);
  gtk_table_attach (GTK_TABLE (table3), lcd_low_white, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 1, 1);

  lcd_hi_white = gtk_drawing_area_new ();
  gtk_widget_show (lcd_hi_white);
  gtk_table_attach (GTK_TABLE (table3), lcd_hi_white, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 1, 1);

  lcd_hi_black = gtk_drawing_area_new ();
  gtk_widget_show (lcd_hi_black);
  gtk_table_attach (GTK_TABLE (table3), lcd_hi_black, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 1, 1);

  lcd_low_black = gtk_drawing_area_new ();
  gtk_widget_show (lcd_low_black);
  gtk_table_attach (GTK_TABLE (table3), lcd_low_black, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 1, 1);

  lcd_custom_white = gtk_drawing_area_new ();
  gtk_widget_show (lcd_custom_white);
  gtk_table_attach (GTK_TABLE (table3), lcd_custom_white, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 1, 1);

  lcd_custom_black = gtk_drawing_area_new ();
  gtk_widget_show (lcd_custom_black);
  gtk_table_attach (GTK_TABLE (table3), lcd_custom_black, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 1, 1);

  label6 = gtk_label_new (_("LCD color"));
  gtk_widget_show (label6);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label6);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);

  dialog_action_area2 = GTK_DIALOG (prop_dialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  prop_dlg_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (prop_dlg_cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (prop_dialog), prop_dlg_cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (prop_dlg_cancel, GTK_CAN_DEFAULT);

  prop_dlg_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (prop_dlg_ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (prop_dialog), prop_dlg_ok, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (prop_dlg_ok, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) prop_dialog, "delete_event",
                    G_CALLBACK (on_prop_dialog_delete_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) prop_dialog, "destroy_event",
                    G_CALLBACK (on_prop_dialog_delete_destroy_event),
                    NULL);

  gtk_widget_add_events(GTK_WIDGET(lcd_custom_white),
			GDK_BUTTON_PRESS_MASK);
  
  gtk_widget_add_events(GTK_WIDGET(lcd_custom_black),
			GDK_BUTTON_PRESS_MASK);

  g_signal_connect ((gpointer) lcd_custom_white, "button_press_event",
                    G_CALLBACK (on_lcd_custom_white_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) lcd_custom_black, "button_press_event",
                    G_CALLBACK (on_lcd_custom_black_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) prop_dlg_cancel, "clicked",
                    G_CALLBACK (on_prop_dlg_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) prop_dlg_ok, "clicked",
                    G_CALLBACK (on_prop_dlg_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prop_dialog, prop_dialog, "prop_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (prop_dialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (prop_dialog, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (prop_dialog, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (prop_dialog, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (prop_dialog, table1, "table1");
  GLADE_HOOKUP_OBJECT (prop_dialog, label3, "label3");
  GLADE_HOOKUP_OBJECT (prop_dialog, label4, "label4");
  GLADE_HOOKUP_OBJECT (prop_dialog, prop_entry_title, "prop_entry_title");
  GLADE_HOOKUP_OBJECT (prop_dialog, prop_entry_author, "prop_entry_author");
  GLADE_HOOKUP_OBJECT (prop_dialog, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (prop_dialog, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (prop_dialog, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (prop_dialog, table2, "table2");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti73, "ti73");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti82, "ti82");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti83, "ti83");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti83p, "ti83p");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti84p, "ti84p");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti85, "ti85");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti86, "ti86");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti89, "ti89");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti89t, "ti89t");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti92, "ti92");
  GLADE_HOOKUP_OBJECT (prop_dialog, ti92p, "ti92p");
  GLADE_HOOKUP_OBJECT (prop_dialog, v200, "v200");
  GLADE_HOOKUP_OBJECT (prop_dialog, label5, "label5");
  GLADE_HOOKUP_OBJECT (prop_dialog, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (prop_dialog, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (prop_dialog, table3, "table3");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_high_contrast, "lcd_high_contrast");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_low_contrast, "lcd_low_contrast");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_custom, "lcd_custom");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_low_white, "lcd_low_white");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_hi_white, "lcd_hi_white");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_hi_black, "lcd_hi_black");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_low_black, "lcd_low_black");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_custom_white, "lcd_custom_white");
  GLADE_HOOKUP_OBJECT (prop_dialog, lcd_custom_black, "lcd_custom_black");
  GLADE_HOOKUP_OBJECT (prop_dialog, label6, "label6");
  GLADE_HOOKUP_OBJECT_NO_REF (prop_dialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (prop_dialog, prop_dlg_cancel, "prop_dlg_cancel");
  GLADE_HOOKUP_OBJECT (prop_dialog, prop_dlg_ok, "prop_dlg_ok");

  return prop_dialog;
}

