.TH TIEMU 1 "March 28, 2007"
.SH NAME
tiemu - a TI's hand-helds emulator (m68k-based)
.SH SYNOPSYS
\fBtiemu\fP [-h] [-v] [--help] [--version] [--import] [-rom=] [-tib=] [-sav=] [filename] 
.SH DESCRIPTION
The \fBTiEmu\fP program allows you to emulate a Texas Instruments calculator such as TI89, TI89 Titanium, TI92, TI92+ or V200PLT.
The emulator has also a virtual link capability which allows to connect it to another program (such as TiLP for instance).
.SH OPTIONS
The command line options override the default options (startup options) and the config file options even.
The \fBTiEmu\fP program accepts the following options:
.TP
\fB-h, --help\fP
Display a list of all command line options.
.TP
\fB-v, --version\fP
Output the version info.
.TP
\fB--import=\fP
Import ROM or TIB into repository and exit. Can be used for creating images (as an example).
This flag must be set before -rom or -tib !
.TP
\fB-rom=\fP
Convert and use the specified dump as image. Note that the image is added to the image repository.
Provided for compatibility.
.TP
\fB-tib=\fP
Convert and use the specified tib/upgrade as image. Idem.
Provided for compatibility.
.TP
\fB-sav=\fP
Load the specified state file. Must be a valid state image and target for emulated calculator.
Provided for compatibility.
.TP
\fBfilename\fP
Load a ROM/TIB/SAV file. ROM & TIB files are converted and added to images repository. Image corresponding
to SAV file is automatically loaded and state is load.

.SH CONFIG FILE FORMAT
This section describes the format of the .tiemu config file which is in the home directory of the 
user (Linux) or in the Program Files folder (Win32). A line preceded by the '#' symbol is a comment. 
Each line has the following format: key=value.
The config file must have the 'RC_END' string at end.
Every line can be put in any order.
Take in mind that any comment added in the config file will be overwritten.
Below is described each option and the possible values:

\fBcalctype=\fP
Defines the calculator type for link parameter. Valid values are: ti89, ti89t, ti92, ti92+, v200.
Note: don't need to touch this setting, it's overridden by TiEmu. Kept for compatibility.

\fBlinktype=\fP
Define the link cable type. Choose one of the following value: none, parallel, serial, TIGraphLink, virtual, TiEmulator, VTi, UsbGraphLink.

\fBport=\fP
Define a link port to use. Can be: null, user, parallel port #1|2|3, serial port #1|2|3|4, virtual port #1|2, USB port #1.

\fBmethod=\fP
Define an I/O method to use. Possible values are: automatic, asm, api, driver, null.

\fBadr_port=\fP
places the I/O address of the I/O port to use. It can be 0x3F8 for a serial port or 0x378 for a parallel port for instance.

\fBserial_device=\fP
places the character device name of the serial port to use with a Grey TIGL.

\fBtimeout=\fP
with the timeout value to use in tenth of seconds. Default value: 20.

\fBdelay=\fP
with the delay value to use in micro-seconds for home-made cables. Default value: 10

\fBbackground=\fP
Define whether TiEmu display the whole frame (keyboard+LCD) or just the LCD screen. Set to 0 if you do not want to use the keyboard.

\fBskin_file=\fP
Define the custom skin file to use. Must be a full path name.

\fBkeys_file=\fP
Define the keymap to use. Must be a full path name.

\fBimg_file=\fP
Define the TiEmu image to load at startup. Must be a full path name.

\fBtib_file=\fP
Define the FLASH upgrade (tib or .9xu/.89u) to load after the image. Must be a full path name.

\fBsav_file=\fP
Define the calculator state image to load at startup.

\fBcpu_rate=\fP
Give the number of instructions executed by the M68000 per 30ms timeslice. Default value is -1 (50000 insts/30ms).

\fBhw_rate=\fP
Give the OS2/OSC3 oscillator rate. Default value is -1 (427 on hw1 and 732 on hw2; OSC2 is incremented every 6250 OSC1 cycles).

\fBlcd_rate=\fP
Define the frame rate of LCD refresh. Default value is -1 (25ms => 40fps). Don't use a value smaller than 10ms.

\fBimg_format=\fP
Defines the image format of the screenshots. Several formats are available: jpg, png and ico.

\fBimg_type=\fP
You can do B/W (bw) or colored (color) screenshots.

\fBimg_size=\fP
The size of the image that is to say you can shots only the LCD (lcd) or the entire window (skin).

\fBscreen_file=\fP
Defines the base filename where the screenshot will be stored.

\fBscreen_counter=\fP
This allows you to save the current screenshot counter. In fact, the resulting filename is computed as 'screenfile[screen_counter].[img_format]. Example: 'screenshot001.png'.

\fBscreen_shots=\fP
Number of frames to capture.

\fBscreen_skips=\fP
Number of frame to skip between 2 captures.

\fBconsole=\fP
Available under Windows platform only. You can hide (no) or show (yes) the DOS console at startup or even display it only during boot (boot).

\fBkbd_dbg=\fP
Display key bindings in the console if set (yes). Else, do nothing (no).

\fBfs_type=\fP
TiEmu supports several file selectors for better integration.
The following options are supported:
.br
- native: native one (default): Win32 on Windows, KDE if built with KDE support and running under KDE, GTK+ 2.x else, 
.br
- old: GTK 1.2 file selector, 
.br
- new: GTK 2.x file selector (advanced capabilities and can show hidden files), 
.br
- win32: deprecated (same as native), 
.br
- kde: KDE file selector (only available if TiEmu is built with KDE support).

\fBbkpts_wnd=\fP
.br
\fBcode_wnd=\fP
.br
\fBmem_wnd=\fP
.br
\fBregs_wnd=\fP
.br
\fBpclog_wnd=\fP
.br
\fBstack_wnd=\fP
.br
\fBheap_wnd=\fP
Set geometry hints for the different windows of the debugger. The format is (x,y,w,h,m,v) where 
x&y are coordinates, w&h are the size, m is set if window is minimized and v is set if the window
is open.
.br
\fBdbg_font_type=\fP
Enable custom font if set to "custom"; use default font if set to "default".
.br
\fBdbg_font_name=\fP
Name of font to use. It must be a valid Pango description font name: a string representation in the form 
"[FAMILY-LIST] [STYLE-OPTIONS] [SIZE]", where FAMILY-LIST is a comma separated list of families optionally terminated by 
a comma, STYLE_OPTIONS is a whitespace separated list of words where each WORD describes one of style, variant, weight, or stretch, 
and SIZE is an decimal number (size in points). Any one of the options may be absent. If FAMILY-LIST is absent, then the 
family_name field of the resulting font description will be initialized to NULL. If STYLE-OPTIONS is missing, then all style 
options will be set to the default values. If SIZE is missing, the size in the resulting font description will be set to 0.


Think to terminate your config script with the 'RC_END' word !!!

.SH COPYRIGHT
Copyright (C) 2000-2001, Romain Lievin and Thomas Corvazier. 
Copyright (C) 2001-2003, Romain Lievin
Copyright (C) 2003, Julien Blache
Copyright (C) 2004, Romain Lievin
Copyright (C) 2005-2007, Romain Lievin and Kevin Kofler

Permission to use, copy, modify, and distribute this software and its documentation for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation.

This program and its source code is distributed under the terms of the 
terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

.SH SUGGESTIONS AND BUG REPORTS
The  canonical place to find TiEmu and some miscellenaous informations is at <http://lpg.ticalc.org/prj_tiemu>.
You can also take a look at <http://lpg.ticalc.org> and <http://www.ticalc.org> for others TI related programs for Linux.

.SH SEE ALSO
tilp(1) for the use of a linking program. TiEmu shares the same communication box for link settings.

.SH SPECIAL THANKS
- Jonas Minnberg (Sasq) for Tiger
.br
- UAE, the Universal Amiga Emulator
.br
- Kevin Kofler <Kevin@tigcc.ticalc.org> for creating rpm packages (Fedora): he is the official maintainer of this package.
.br
- Julien Blache <jb@jblache.org> for creating deb packages (Debian): he is the official maintainer of this package.

.SH AUTHOR
Romain Lievin
Kevin Kofler
