/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "dump_cb.h"
#include "dump_dbox.h"
#include "support.h"

GtkWidget*
create_ramdump_fileselection (void)
{
  GtkWidget *ramdump_fileselection;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  ramdump_fileselection = gtk_file_selection_new (_("Select a ROM to load"));
  gtk_widget_set_name (ramdump_fileselection, "ramdump_fileselection");
  gtk_object_set_data (GTK_OBJECT (ramdump_fileselection), "ramdump_fileselection", ramdump_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (ramdump_fileselection), 10);
  gtk_window_set_modal (GTK_WINDOW (ramdump_fileselection), TRUE);

  ok_button2 = GTK_FILE_SELECTION (ramdump_fileselection)->ok_button;
  gtk_widget_set_name (ok_button2, "ok_button2");
  gtk_object_set_data (GTK_OBJECT (ramdump_fileselection), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (ramdump_fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button2, "cancel_button2");
  gtk_object_set_data (GTK_OBJECT (ramdump_fileselection), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (ramdump_fileselection), "destroy",
                      GTK_SIGNAL_FUNC (on_ramdump_fileselection_destroy),
                      ramdump_fileselection);
  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_ramd_ok_button2_clicked),
                      ramdump_fileselection);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_ramd_cancel_button2_clicked),
                      ramdump_fileselection);

  gtk_window_add_accel_group (GTK_WINDOW (ramdump_fileselection), accel_group);

  return ramdump_fileselection;
}

GtkWidget*
create_romdump_fileselection (void)
{
  GtkWidget *romdump_fileselection;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  romdump_fileselection = gtk_file_selection_new (_("Select a ROM to load"));
  gtk_widget_set_name (romdump_fileselection, "romdump_fileselection");
  gtk_object_set_data (GTK_OBJECT (romdump_fileselection), "romdump_fileselection", romdump_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (romdump_fileselection), 10);
  gtk_window_set_modal (GTK_WINDOW (romdump_fileselection), TRUE);

  ok_button2 = GTK_FILE_SELECTION (romdump_fileselection)->ok_button;
  gtk_widget_set_name (ok_button2, "ok_button2");
  gtk_object_set_data (GTK_OBJECT (romdump_fileselection), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (romdump_fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button2, "cancel_button2");
  gtk_object_set_data (GTK_OBJECT (romdump_fileselection), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (romdump_fileselection), "destroy",
                      GTK_SIGNAL_FUNC (on_romd_fileselection_destroy),
                      romdump_fileselection);
  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_romd_ok_button2_clicked),
                      romdump_fileselection);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_romd_cancel_button2_clicked),
                      romdump_fileselection);

  gtk_window_add_accel_group (GTK_WINDOW (romdump_fileselection), accel_group);

  return romdump_fileselection;
}

GtkWidget*
create_wait_conversion_dbox (void)
{
  GtkWidget *wait_conversion_dbox;
  GtkWidget *label1;

  wait_conversion_dbox = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (wait_conversion_dbox, "wait_conversion_dbox");
  gtk_object_set_data (GTK_OBJECT (wait_conversion_dbox), "wait_conversion_dbox", wait_conversion_dbox);
  gtk_window_set_title (GTK_WINDOW (wait_conversion_dbox), _("In progress..."));
  gtk_window_set_policy (GTK_WINDOW (wait_conversion_dbox), FALSE, TRUE, TRUE);

  label1 = gtk_label_new (_("File is being written. \nPlease wait..."));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (wait_conversion_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (wait_conversion_dbox), label1);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 10, 10);

  return wait_conversion_dbox;
}

