/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_rom_fileselection (void);
GtkWidget* create_tifile_fileselection (void);
GtkWidget* create_tib_fileselection (void);
GtkWidget* create_ams_fileselection (void);
