/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "tiemu_cb.h"
#include "tiemu_dbox.h"
#include "support.h"

GtkWidget*
create_popup_menu (void)
{
  GtkWidget *popup_menu;
  GtkAccelGroup *popup_menu_accels;
  GtkWidget *popup_menu_header;
  GtkWidget *separator10;
  guint tmp_key;
  GtkWidget *send_file_to_gtktiemu1;
  GtkWidget *link_cable1;
  GtkWidget *separator11;
  GtkWidget *config1;
  GtkWidget *config1_menu;
  GtkAccelGroup *config1_menu_accels;
  GtkWidget *save_config1;
  GtkWidget *load_config1;
  GtkWidget *calculator_state1;
  GtkWidget *calculator_state1_menu;
  GtkAccelGroup *calculator_state1_menu_accels;
  GtkWidget *load_state_image1;
  GtkWidget *save_state_image1;
  GtkWidget *revert_to_saved_state1;
  GtkWidget *separator20;
  GtkWidget *enter_debugger1;
  GtkWidget *reset_calc1;
  GtkWidget *separator12;
  GtkWidget *emulator_options1;
  GtkWidget *emulator_options1_menu;
  GtkAccelGroup *emulator_options1_menu_accels;
  GtkWidget *speed2;
  GtkWidget *speed2_menu;
  GtkAccelGroup *speed2_menu_accels;
  GtkWidget *restrict1;
  GtkWidget *change_speed1;
  GtkWidget *cycle_rate1;
  GtkWidget *itick1;
  GtkWidget *sync1;
  GtkWidget *number_of_colors1;
  GtkWidget *screen1;
  GtkWidget *screen1_menu;
  GtkAccelGroup *screen1_menu_accels;
  GtkWidget *normal_view__1x_1;
  GtkWidget *large_view__x2_1;
  GtkWidget *full_screen1;
  GtkWidget *skin_for_current_calc1;
  GtkWidget *skin_for_current_calc1_menu;
  GtkAccelGroup *skin_for_current_calc1_menu_accels;
  GtkWidget *skin1;
  GtkWidget *none1;
  GtkWidget *set_skin1;
  GtkWidget *screenshot1;
  GtkWidget *screenshot1_menu;
  GtkAccelGroup *screenshot1_menu_accels;
  GtkWidget *now__1;
  GtkWidget *options1;
  GtkWidget *ram1;
  GtkWidget *ram1_menu;
  GtkAccelGroup *ram1_menu_accels;
  GtkWidget *dump_ram1;
  GtkWidget *rom1;
  GtkWidget *rom1_menu;
  GtkAccelGroup *rom1_menu_accels;
  GtkWidget *dump_rom1;
  GtkWidget *rom_file1;
  GtkWidget *set_rom1;
  GtkWidget *separator13;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *help3;
  GtkWidget *manpage1;
  GtkWidget *separator15;
  GtkWidget *changelog1;
  GtkWidget *separator14;
  GtkWidget *thanks1;
  GtkWidget *about1;
  GtkWidget *infos1;
  GtkWidget *exit1;
  GtkWidget *exit_without_saving_state1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  popup_menu = gtk_menu_new ();
  gtk_widget_set_name (popup_menu, "popup_menu");
  gtk_object_set_data (GTK_OBJECT (popup_menu), "popup_menu", popup_menu);
  popup_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (popup_menu));

  popup_menu_header = gtk_menu_item_new_with_label (_("TiEmu II menu (v2.0)"));
  gtk_widget_set_name (popup_menu_header, "popup_menu_header");
  gtk_widget_ref (popup_menu_header);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "popup_menu_header", popup_menu_header,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_menu_header);
  gtk_container_add (GTK_CONTAINER (popup_menu), popup_menu_header);

  separator10 = gtk_menu_item_new ();
  gtk_widget_set_name (separator10, "separator10");
  gtk_widget_ref (separator10);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "separator10", separator10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator10);
  gtk_container_add (GTK_CONTAINER (popup_menu), separator10);
  gtk_widget_set_sensitive (separator10, FALSE);

  send_file_to_gtktiemu1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (send_file_to_gtktiemu1)->child),
                                   _("Send _file to TIEmu"));
  gtk_widget_add_accelerator (send_file_to_gtktiemu1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (send_file_to_gtktiemu1, "send_file_to_gtktiemu1");
  gtk_widget_ref (send_file_to_gtktiemu1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "send_file_to_gtktiemu1", send_file_to_gtktiemu1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (send_file_to_gtktiemu1);
  gtk_container_add (GTK_CONTAINER (popup_menu), send_file_to_gtktiemu1);
  gtk_tooltips_set_tip (tooltips, send_file_to_gtktiemu1, _("Send the selected file to the emulator. This file can be of any type (single, group, backup, FLASH app or FLASH OS)."), NULL);
  gtk_widget_add_accelerator (send_file_to_gtktiemu1, "activate", accel_group,
                              GDK_F10, 0,
                              GTK_ACCEL_VISIBLE);

  link_cable1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (link_cable1)->child),
                                   _("Link _options..."));
  gtk_widget_add_accelerator (link_cable1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (link_cable1, "link_cable1");
  gtk_widget_ref (link_cable1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "link_cable1", link_cable1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (link_cable1);
  gtk_container_add (GTK_CONTAINER (popup_menu), link_cable1);
  gtk_tooltips_set_tip (tooltips, link_cable1, _("Link cable setup"), NULL);

  separator11 = gtk_menu_item_new ();
  gtk_widget_set_name (separator11, "separator11");
  gtk_widget_ref (separator11);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "separator11", separator11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator11);
  gtk_container_add (GTK_CONTAINER (popup_menu), separator11);
  gtk_widget_set_sensitive (separator11, FALSE);

  config1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (config1)->child),
                                   _("_Configuration"));
  gtk_widget_add_accelerator (config1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (config1, "config1");
  gtk_widget_ref (config1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "config1", config1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (config1);
  gtk_container_add (GTK_CONTAINER (popup_menu), config1);

  config1_menu = gtk_menu_new ();
  gtk_widget_set_name (config1_menu, "config1_menu");
  gtk_widget_ref (config1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "config1_menu", config1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (config1), config1_menu);
  config1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (config1_menu));

  save_config1 = gtk_menu_item_new_with_label (_("Save config..."));
  gtk_widget_set_name (save_config1, "save_config1");
  gtk_widget_ref (save_config1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "save_config1", save_config1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save_config1);
  gtk_container_add (GTK_CONTAINER (config1_menu), save_config1);
  gtk_tooltips_set_tip (tooltips, save_config1, _("Save the actual configuration"), NULL);

  load_config1 = gtk_menu_item_new_with_label (_("Load config..."));
  gtk_widget_set_name (load_config1, "load_config1");
  gtk_widget_ref (load_config1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "load_config1", load_config1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load_config1);
  gtk_container_add (GTK_CONTAINER (config1_menu), load_config1);
  gtk_tooltips_set_tip (tooltips, load_config1, _("Load the configuration previously saved"), NULL);

  calculator_state1 = gtk_menu_item_new_with_label (_("Calculator state"));
  gtk_widget_set_name (calculator_state1, "calculator_state1");
  gtk_widget_ref (calculator_state1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "calculator_state1", calculator_state1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (calculator_state1);
  gtk_container_add (GTK_CONTAINER (popup_menu), calculator_state1);

  calculator_state1_menu = gtk_menu_new ();
  gtk_widget_set_name (calculator_state1_menu, "calculator_state1_menu");
  gtk_widget_ref (calculator_state1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "calculator_state1_menu", calculator_state1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (calculator_state1), calculator_state1_menu);
  calculator_state1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (calculator_state1_menu));

  load_state_image1 = gtk_menu_item_new_with_label (_("Load state image..."));
  gtk_widget_set_name (load_state_image1, "load_state_image1");
  gtk_widget_ref (load_state_image1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "load_state_image1", load_state_image1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load_state_image1);
  gtk_container_add (GTK_CONTAINER (calculator_state1_menu), load_state_image1);

  save_state_image1 = gtk_menu_item_new_with_label (_("Save state image..."));
  gtk_widget_set_name (save_state_image1, "save_state_image1");
  gtk_widget_ref (save_state_image1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "save_state_image1", save_state_image1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save_state_image1);
  gtk_container_add (GTK_CONTAINER (calculator_state1_menu), save_state_image1);

  revert_to_saved_state1 = gtk_menu_item_new_with_label (_("Revert to saved state"));
  gtk_widget_set_name (revert_to_saved_state1, "revert_to_saved_state1");
  gtk_widget_ref (revert_to_saved_state1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "revert_to_saved_state1", revert_to_saved_state1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (revert_to_saved_state1);
  gtk_container_add (GTK_CONTAINER (calculator_state1_menu), revert_to_saved_state1);

  separator20 = gtk_menu_item_new ();
  gtk_widget_set_name (separator20, "separator20");
  gtk_widget_ref (separator20);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "separator20", separator20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator20);
  gtk_container_add (GTK_CONTAINER (popup_menu), separator20);
  gtk_widget_set_sensitive (separator20, FALSE);

  enter_debugger1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (enter_debugger1)->child),
                                   _("Enter _debugger..."));
  gtk_widget_add_accelerator (enter_debugger1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (enter_debugger1, "enter_debugger1");
  gtk_widget_ref (enter_debugger1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "enter_debugger1", enter_debugger1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (enter_debugger1);
  gtk_container_add (GTK_CONTAINER (popup_menu), enter_debugger1);
  gtk_tooltips_set_tip (tooltips, enter_debugger1, _("Go to debugger"), NULL);
  gtk_widget_add_accelerator (enter_debugger1, "activate", accel_group,
                              GDK_F9, 0,
                              GTK_ACCEL_VISIBLE);

  reset_calc1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (reset_calc1)->child),
                                   _("_Reset calc"));
  gtk_widget_add_accelerator (reset_calc1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (reset_calc1, "reset_calc1");
  gtk_widget_ref (reset_calc1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "reset_calc1", reset_calc1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reset_calc1);
  gtk_container_add (GTK_CONTAINER (popup_menu), reset_calc1);

  separator12 = gtk_menu_item_new ();
  gtk_widget_set_name (separator12, "separator12");
  gtk_widget_ref (separator12);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "separator12", separator12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator12);
  gtk_container_add (GTK_CONTAINER (popup_menu), separator12);
  gtk_widget_set_sensitive (separator12, FALSE);

  emulator_options1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (emulator_options1)->child),
                                   _("Emulator _options"));
  gtk_widget_add_accelerator (emulator_options1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (emulator_options1, "emulator_options1");
  gtk_widget_ref (emulator_options1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "emulator_options1", emulator_options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (emulator_options1);
  gtk_container_add (GTK_CONTAINER (popup_menu), emulator_options1);

  emulator_options1_menu = gtk_menu_new ();
  gtk_widget_set_name (emulator_options1_menu, "emulator_options1_menu");
  gtk_widget_ref (emulator_options1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "emulator_options1_menu", emulator_options1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (emulator_options1), emulator_options1_menu);
  emulator_options1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (emulator_options1_menu));

  speed2 = gtk_menu_item_new_with_label (_("Speed"));
  gtk_widget_set_name (speed2, "speed2");
  gtk_widget_ref (speed2);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "speed2", speed2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (speed2);
  gtk_container_add (GTK_CONTAINER (emulator_options1_menu), speed2);

  speed2_menu = gtk_menu_new ();
  gtk_widget_set_name (speed2_menu, "speed2_menu");
  gtk_widget_ref (speed2_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "speed2_menu", speed2_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (speed2), speed2_menu);
  speed2_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (speed2_menu));

  restrict1 = gtk_check_menu_item_new_with_label (_("Restrict to actual speed"));
  gtk_widget_set_name (restrict1, "restrict1");
  gtk_widget_ref (restrict1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "restrict1", restrict1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (restrict1);
  gtk_container_add (GTK_CONTAINER (speed2_menu), restrict1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (restrict1), TRUE);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (restrict1), TRUE);

  change_speed1 = gtk_menu_item_new_with_label (_("Tickrate..."));
  gtk_widget_set_name (change_speed1, "change_speed1");
  gtk_widget_ref (change_speed1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "change_speed1", change_speed1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (change_speed1);
  gtk_container_add (GTK_CONTAINER (speed2_menu), change_speed1);
  gtk_tooltips_set_tip (tooltips, change_speed1, _("Set number the rate of the timer"), NULL);

  cycle_rate1 = gtk_menu_item_new_with_label (_("Cycle rate..."));
  gtk_widget_set_name (cycle_rate1, "cycle_rate1");
  gtk_widget_ref (cycle_rate1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "cycle_rate1", cycle_rate1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cycle_rate1);
  gtk_container_add (GTK_CONTAINER (speed2_menu), cycle_rate1);
  gtk_tooltips_set_tip (tooltips, cycle_rate1, _("Set the rate of instructions"), NULL);

  itick1 = gtk_menu_item_new_with_label (_("Itick"));
  gtk_widget_set_name (itick1, "itick1");
  gtk_widget_ref (itick1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "itick1", itick1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (itick1);
  gtk_container_add (GTK_CONTAINER (speed2_menu), itick1);
  gtk_tooltips_set_tip (tooltips, itick1, _("Set numbers of instructions per timertick"), NULL);

  sync1 = gtk_check_menu_item_new_with_label (_("Sync"));
  gtk_widget_set_name (sync1, "sync1");
  gtk_widget_ref (sync1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "sync1", sync1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sync1);
  gtk_container_add (GTK_CONTAINER (speed2_menu), sync1);
  gtk_tooltips_set_tip (tooltips, sync1, _("If you uncheck this, screen updating will be synchronized with the timer which means it always be updated regularly. This may cause grayscale pictures to flicker when you press keys and other things happen in the code. If you check this, screen updating will be synced with IRQ 1. This means that if IRQ 1 does not run, the screen is not updated. This options usually makes grayscales rock-stable, but wont work at all in programs that turn off IRQ 1 (like \"tunnel\" and \"torus\")."), NULL);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (sync1), TRUE);

  number_of_colors1 = gtk_menu_item_new_with_label (_("Number of colors..."));
  gtk_widget_set_name (number_of_colors1, "number_of_colors1");
  gtk_widget_ref (number_of_colors1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "number_of_colors1", number_of_colors1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (number_of_colors1);
  gtk_container_add (GTK_CONTAINER (emulator_options1_menu), number_of_colors1);
  gtk_tooltips_set_tip (tooltips, number_of_colors1, _("Set current number of emulated extra grayscales colors"), NULL);

  screen1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (screen1)->child),
                                   _("_Screen"));
  gtk_widget_add_accelerator (screen1, "activate_item", emulator_options1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (screen1, "screen1");
  gtk_widget_ref (screen1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "screen1", screen1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screen1);
  gtk_container_add (GTK_CONTAINER (emulator_options1_menu), screen1);

  screen1_menu = gtk_menu_new ();
  gtk_widget_set_name (screen1_menu, "screen1_menu");
  gtk_widget_ref (screen1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "screen1_menu", screen1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (screen1), screen1_menu);
  screen1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (screen1_menu));

  normal_view__1x_1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (normal_view__1x_1)->child),
                                   _("_Normal view (1x)"));
  gtk_widget_add_accelerator (normal_view__1x_1, "activate_item", screen1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (normal_view__1x_1, "normal_view__1x_1");
  gtk_widget_ref (normal_view__1x_1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "normal_view__1x_1", normal_view__1x_1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (normal_view__1x_1);
  gtk_container_add (GTK_CONTAINER (screen1_menu), normal_view__1x_1);

  large_view__x2_1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (large_view__x2_1)->child),
                                   _("_Large view (x2)"));
  gtk_widget_add_accelerator (large_view__x2_1, "activate_item", screen1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (large_view__x2_1, "large_view__x2_1");
  gtk_widget_ref (large_view__x2_1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "large_view__x2_1", large_view__x2_1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (large_view__x2_1);
  gtk_container_add (GTK_CONTAINER (screen1_menu), large_view__x2_1);

  full_screen1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (full_screen1)->child),
                                   _("_Full screen (Alt+Enter)"));
  gtk_widget_add_accelerator (full_screen1, "activate_item", screen1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (full_screen1, "full_screen1");
  gtk_widget_ref (full_screen1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "full_screen1", full_screen1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (full_screen1);
  gtk_container_add (GTK_CONTAINER (screen1_menu), full_screen1);

  skin_for_current_calc1 = gtk_menu_item_new_with_label (_("Skin for current calc"));
  gtk_widget_set_name (skin_for_current_calc1, "skin_for_current_calc1");
  gtk_widget_ref (skin_for_current_calc1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "skin_for_current_calc1", skin_for_current_calc1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (skin_for_current_calc1);
  gtk_container_add (GTK_CONTAINER (popup_menu), skin_for_current_calc1);

  skin_for_current_calc1_menu = gtk_menu_new ();
  gtk_widget_set_name (skin_for_current_calc1_menu, "skin_for_current_calc1_menu");
  gtk_widget_ref (skin_for_current_calc1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "skin_for_current_calc1_menu", skin_for_current_calc1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (skin_for_current_calc1), skin_for_current_calc1_menu);
  skin_for_current_calc1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (skin_for_current_calc1_menu));

  skin1 = gtk_menu_item_new_with_label (_("Skin92"));
  gtk_widget_set_name (skin1, "skin1");
  gtk_widget_ref (skin1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "skin1", skin1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (skin1);
  gtk_container_add (GTK_CONTAINER (skin_for_current_calc1_menu), skin1);

  none1 = gtk_menu_item_new_with_label (_("None"));
  gtk_widget_set_name (none1, "none1");
  gtk_widget_ref (none1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "none1", none1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (none1);
  gtk_container_add (GTK_CONTAINER (skin_for_current_calc1_menu), none1);

  set_skin1 = gtk_menu_item_new_with_label (_("Set skin..."));
  gtk_widget_set_name (set_skin1, "set_skin1");
  gtk_widget_ref (set_skin1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "set_skin1", set_skin1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (set_skin1);
  gtk_container_add (GTK_CONTAINER (skin_for_current_calc1_menu), set_skin1);

  screenshot1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (screenshot1)->child),
                                   _("_Screenshot"));
  gtk_widget_add_accelerator (screenshot1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (screenshot1, "screenshot1");
  gtk_widget_ref (screenshot1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "screenshot1", screenshot1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot1);
  gtk_container_add (GTK_CONTAINER (popup_menu), screenshot1);

  screenshot1_menu = gtk_menu_new ();
  gtk_widget_set_name (screenshot1_menu, "screenshot1_menu");
  gtk_widget_ref (screenshot1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "screenshot1_menu", screenshot1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (screenshot1), screenshot1_menu);
  screenshot1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (screenshot1_menu));

  now__1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (now__1)->child),
                                   _("_Now !"));
  gtk_widget_add_accelerator (now__1, "activate_item", screenshot1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (now__1, "now__1");
  gtk_widget_ref (now__1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "now__1", now__1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (now__1);
  gtk_container_add (GTK_CONTAINER (screenshot1_menu), now__1);
  gtk_widget_add_accelerator (now__1, "activate", accel_group,
                              GDK_F10, 0,
                              GTK_ACCEL_VISIBLE);

  options1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (options1)->child),
                                   _("_Options"));
  gtk_widget_add_accelerator (options1, "activate_item", screenshot1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (options1, "options1");
  gtk_widget_ref (options1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "options1", options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (screenshot1_menu), options1);

  ram1 = gtk_menu_item_new_with_label (_("RAM"));
  gtk_widget_set_name (ram1, "ram1");
  gtk_widget_ref (ram1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "ram1", ram1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ram1);
  gtk_container_add (GTK_CONTAINER (popup_menu), ram1);
  gtk_tooltips_set_tip (tooltips, ram1, _("RAM parameters"), NULL);

  ram1_menu = gtk_menu_new ();
  gtk_widget_set_name (ram1_menu, "ram1_menu");
  gtk_widget_ref (ram1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "ram1_menu", ram1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (ram1), ram1_menu);
  ram1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (ram1_menu));

  dump_ram1 = gtk_menu_item_new_with_label (_("Dump RAM..."));
  gtk_widget_set_name (dump_ram1, "dump_ram1");
  gtk_widget_ref (dump_ram1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "dump_ram1", dump_ram1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dump_ram1);
  gtk_container_add (GTK_CONTAINER (ram1_menu), dump_ram1);

  rom1 = gtk_menu_item_new_with_label (_("ROM"));
  gtk_widget_set_name (rom1, "rom1");
  gtk_widget_ref (rom1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "rom1", rom1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rom1);
  gtk_container_add (GTK_CONTAINER (popup_menu), rom1);
  gtk_tooltips_set_tip (tooltips, rom1, _("ROM parameters"), NULL);

  rom1_menu = gtk_menu_new ();
  gtk_widget_set_name (rom1_menu, "rom1_menu");
  gtk_widget_ref (rom1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "rom1_menu", rom1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (rom1), rom1_menu);
  rom1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (rom1_menu));

  dump_rom1 = gtk_menu_item_new_with_label (_("Dump ROM..."));
  gtk_widget_set_name (dump_rom1, "dump_rom1");
  gtk_widget_ref (dump_rom1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "dump_rom1", dump_rom1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dump_rom1);
  gtk_container_add (GTK_CONTAINER (rom1_menu), dump_rom1);
  gtk_tooltips_set_tip (tooltips, dump_rom1, _("Make a ROM dump to link port"), NULL);

  rom_file1 = gtk_menu_item_new_with_label (_("Add image/upgrade..."));
  gtk_widget_set_name (rom_file1, "rom_file1");
  gtk_widget_ref (rom_file1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "rom_file1", rom_file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rom_file1);
  gtk_container_add (GTK_CONTAINER (rom1_menu), rom_file1);
  gtk_tooltips_set_tip (tooltips, rom_file1, _("Add a ROM image or a FLASH upgrade..."), NULL);

  set_rom1 = gtk_menu_item_new_with_label (_("Set ROM (image/upgrade)"));
  gtk_widget_set_name (set_rom1, "set_rom1");
  gtk_widget_ref (set_rom1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "set_rom1", set_rom1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (set_rom1);
  gtk_container_add (GTK_CONTAINER (rom1_menu), set_rom1);
  gtk_tooltips_set_tip (tooltips, set_rom1, _("Set emulation ROM version"), NULL);

  separator13 = gtk_menu_item_new ();
  gtk_widget_set_name (separator13, "separator13");
  gtk_widget_ref (separator13);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "separator13", separator13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator13);
  gtk_container_add (GTK_CONTAINER (popup_menu), separator13);
  gtk_widget_set_sensitive (separator13, FALSE);

  help1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help1)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (help1, "help1");
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (popup_menu), help1);

  help1_menu = gtk_menu_new ();
  gtk_widget_set_name (help1_menu, "help1_menu");
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  help3 = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_set_name (help3, "help3");
  gtk_widget_ref (help3);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "help3", help3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help3);
  gtk_container_add (GTK_CONTAINER (help1_menu), help3);
  gtk_widget_add_accelerator (help3, "activate", accel_group,
                              GDK_H, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  manpage1 = gtk_menu_item_new_with_label (_("Manpage"));
  gtk_widget_set_name (manpage1, "manpage1");
  gtk_widget_ref (manpage1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "manpage1", manpage1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage1);
  gtk_container_add (GTK_CONTAINER (help1_menu), manpage1);
  gtk_widget_add_accelerator (manpage1, "activate", accel_group,
                              GDK_M, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator15 = gtk_menu_item_new ();
  gtk_widget_set_name (separator15, "separator15");
  gtk_widget_ref (separator15);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "separator15", separator15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator15);
  gtk_container_add (GTK_CONTAINER (help1_menu), separator15);
  gtk_widget_set_sensitive (separator15, FALSE);

  changelog1 = gtk_menu_item_new_with_label (_("ChangeLog"));
  gtk_widget_set_name (changelog1, "changelog1");
  gtk_widget_ref (changelog1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "changelog1", changelog1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (changelog1);
  gtk_container_add (GTK_CONTAINER (help1_menu), changelog1);

  separator14 = gtk_menu_item_new ();
  gtk_widget_set_name (separator14, "separator14");
  gtk_widget_ref (separator14);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "separator14", separator14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator14);
  gtk_container_add (GTK_CONTAINER (help1_menu), separator14);
  gtk_widget_set_sensitive (separator14, FALSE);

  thanks1 = gtk_menu_item_new_with_label (_("Thanks"));
  gtk_widget_set_name (thanks1, "thanks1");
  gtk_widget_ref (thanks1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "thanks1", thanks1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (thanks1);
  gtk_container_add (GTK_CONTAINER (help1_menu), thanks1);

  about1 = gtk_menu_item_new_with_label (_("About..."));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);
  gtk_tooltips_set_tip (tooltips, about1, _("More informations"), NULL);

  infos1 = gtk_menu_item_new_with_label (_("Infos..."));
  gtk_widget_set_name (infos1, "infos1");
  gtk_widget_ref (infos1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "infos1", infos1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (infos1);
  gtk_container_add (GTK_CONTAINER (popup_menu), infos1);

  exit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit1)->child),
                                   _("E_xit and save state"));
  gtk_widget_add_accelerator (exit1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (exit1, "exit1");
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (popup_menu), exit1);

  exit_without_saving_state1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit_without_saving_state1)->child),
                                   _("Exit _without saving state"));
  gtk_widget_add_accelerator (exit_without_saving_state1, "activate_item", popup_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (exit_without_saving_state1, "exit_without_saving_state1");
  gtk_widget_ref (exit_without_saving_state1);
  gtk_object_set_data_full (GTK_OBJECT (popup_menu), "exit_without_saving_state1", exit_without_saving_state1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit_without_saving_state1);
  gtk_container_add (GTK_CONTAINER (popup_menu), exit_without_saving_state1);

  gtk_signal_connect (GTK_OBJECT (popup_menu), "configure_event",
                      GTK_SIGNAL_FUNC (on_popup_menu_configure_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_menu), "cancel",
                      GTK_SIGNAL_FUNC (on_popup_menu_cancel),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_menu), "deactivate",
                      GTK_SIGNAL_FUNC (on_popup_menu_deactivate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_menu_header), "activate",
                      GTK_SIGNAL_FUNC (on_popup_menu_header),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (send_file_to_gtktiemu1), "activate",
                      GTK_SIGNAL_FUNC (on_send_file_to_gtktiemu1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (link_cable1), "activate",
                      GTK_SIGNAL_FUNC (on_link_cable1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save_config1), "activate",
                      GTK_SIGNAL_FUNC (on_save_config1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load_config1), "activate",
                      GTK_SIGNAL_FUNC (on_load_config1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load_state_image1), "activate",
                      GTK_SIGNAL_FUNC (on_load_state_image1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save_state_image1), "activate",
                      GTK_SIGNAL_FUNC (on_save_state_image1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (revert_to_saved_state1), "activate",
                      GTK_SIGNAL_FUNC (on_revert_to_saved_state1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (enter_debugger1), "activate",
                      GTK_SIGNAL_FUNC (on_enter_debugger1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reset_calc1), "activate",
                      GTK_SIGNAL_FUNC (on_reset_calc1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (restrict1), "activate",
                      GTK_SIGNAL_FUNC (on_restrict_to_actual_speed1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (change_speed1), "activate",
                      GTK_SIGNAL_FUNC (on_change_speed1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cycle_rate1), "activate",
                      GTK_SIGNAL_FUNC (on_cycle_rate1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (itick1), "activate",
                      GTK_SIGNAL_FUNC (on_itick1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (sync1), "activate",
                      GTK_SIGNAL_FUNC (on_sync1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (number_of_colors1), "activate",
                      GTK_SIGNAL_FUNC (on_number_of_colors1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (normal_view__1x_1), "activate",
                      GTK_SIGNAL_FUNC (on_normal_view__1x_1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (large_view__x2_1), "activate",
                      GTK_SIGNAL_FUNC (on_large_view__x2_1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (full_screen1), "activate",
                      GTK_SIGNAL_FUNC (on_full_screen1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (skin1), "activate",
                      GTK_SIGNAL_FUNC (on_skin1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (none1), "activate",
                      GTK_SIGNAL_FUNC (on_none1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (set_skin1), "activate",
                      GTK_SIGNAL_FUNC (on_set_skin1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (now__1), "activate",
                      GTK_SIGNAL_FUNC (on_now__1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (options1), "activate",
                      GTK_SIGNAL_FUNC (on_rbm_options1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (dump_ram1), "activate",
                      GTK_SIGNAL_FUNC (on_dump_ram1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (dump_rom1), "activate",
                      GTK_SIGNAL_FUNC (on_dump_rom1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rom_file1), "activate",
                      GTK_SIGNAL_FUNC (on_rom_file1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (set_rom1), "activate",
                      GTK_SIGNAL_FUNC (on_set_rom1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (help3), "activate",
                      GTK_SIGNAL_FUNC (on_help3_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manpage1), "activate",
                      GTK_SIGNAL_FUNC (on_manpage1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (changelog1), "activate",
                      GTK_SIGNAL_FUNC (on_changelog1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (thanks1), "activate",
                      GTK_SIGNAL_FUNC (on_thanks1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (infos1), "activate",
                      GTK_SIGNAL_FUNC (on_infos1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit_without_saving_state1), "activate",
                      GTK_SIGNAL_FUNC (on_exit_without_saving_state1_activate),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (popup_menu), "tooltips", tooltips);

  gtk_menu_set_accel_group (GTK_MENU (popup_menu), accel_group);

  return popup_menu;
}

