/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "trap_cb.h"
#include "trap_dbox.h"
#include "support.h"

GtkWidget*
create_trap_dbox (void)
{
  GtkWidget *trap_dbox;
  GtkWidget *dialog_vbox13;
  GtkWidget *table3;
  GtkWidget *frame25;
  GtkWidget *table4;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *checkbutton8;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton9;
  GtkWidget *frame26;
  GtkWidget *vbox33;
  GtkWidget *checkbutton10;
  GtkWidget *checkbutton11;
  GtkWidget *checkbutton12;
  GtkWidget *checkbutton13;
  GtkWidget *checkbutton15;
  GtkWidget *checkbutton14;
  GtkWidget *frame27;
  GtkWidget *table5;
  GtkWidget *checkbutton16;
  GtkWidget *checkbutton17;
  GtkWidget *checkbutton18;
  GtkWidget *checkbutton19;
  GtkWidget *checkbutton20;
  GtkWidget *checkbutton21;
  GtkWidget *checkbutton22;
  GtkWidget *checkbutton23;
  GtkWidget *checkbutton24;
  GtkWidget *checkbutton25;
  GtkWidget *checkbutton26;
  GtkWidget *checkbutton27;
  GtkWidget *checkbutton28;
  GtkWidget *checkbutton29;
  GtkWidget *checkbutton30;
  guint checkbutton31_key;
  GtkWidget *checkbutton31;
  GtkWidget *dialog_action_area13;
  GtkWidget *hbuttonbox17;
  GtkWidget *button46;
  GtkWidget *hbox1;
  GtkWidget *pixmap1;
  guint label1_key;
  GtkWidget *label1;
  GtkWidget *button47;
  GtkWidget *hbox2;
  GtkWidget *pixmap2;
  guint label2_key;
  GtkWidget *label2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  trap_dbox = gtk_dialog_new ();
  gtk_widget_set_name (trap_dbox, "trap_dbox");
  gtk_object_set_data (GTK_OBJECT (trap_dbox), "trap_dbox", trap_dbox);
  gtk_window_set_title (GTK_WINDOW (trap_dbox), _("Bkreakpoint on trap/exception"));
  gtk_window_set_policy (GTK_WINDOW (trap_dbox), FALSE, FALSE, TRUE);

  dialog_vbox13 = GTK_DIALOG (trap_dbox)->vbox;
  gtk_widget_set_name (dialog_vbox13, "dialog_vbox13");
  gtk_object_set_data (GTK_OBJECT (trap_dbox), "dialog_vbox13", dialog_vbox13);
  gtk_widget_show (dialog_vbox13);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox13), table3, TRUE, TRUE, 0);

  frame25 = gtk_frame_new (_("Exceptions"));
  gtk_widget_set_name (frame25, "frame25");
  gtk_widget_ref (frame25);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "frame25", frame25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame25);
  gtk_table_attach (GTK_TABLE (table3), frame25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame25), 5);

  table4 = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame25), table4);

  checkbutton1 = gtk_check_button_new_with_label (_("Adress error"));
  gtk_widget_set_name (checkbutton1, "checkbutton1");
  gtk_widget_ref (checkbutton1);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton1", checkbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table4), checkbutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton3 = gtk_check_button_new_with_label (_("Illegal instruction"));
  gtk_widget_set_name (checkbutton3, "checkbutton3");
  gtk_widget_ref (checkbutton3);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton3", checkbutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton3);
  gtk_table_attach (GTK_TABLE (table4), checkbutton3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton4 = gtk_check_button_new_with_label (_("Divide by zero"));
  gtk_widget_set_name (checkbutton4, "checkbutton4");
  gtk_widget_ref (checkbutton4);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton4", checkbutton4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton4);
  gtk_table_attach (GTK_TABLE (table4), checkbutton4, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton5 = gtk_check_button_new_with_label (_("CHK instruction"));
  gtk_widget_set_name (checkbutton5, "checkbutton5");
  gtk_widget_ref (checkbutton5);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton5", checkbutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton5);
  gtk_table_attach (GTK_TABLE (table4), checkbutton5, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton6 = gtk_check_button_new_with_label (_("TRAPV instruction"));
  gtk_widget_set_name (checkbutton6, "checkbutton6");
  gtk_widget_ref (checkbutton6);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton6", checkbutton6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton6);
  gtk_table_attach (GTK_TABLE (table4), checkbutton6, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton7 = gtk_check_button_new_with_label (_("Trace"));
  gtk_widget_set_name (checkbutton7, "checkbutton7");
  gtk_widget_ref (checkbutton7);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton7", checkbutton7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton7);
  gtk_table_attach (GTK_TABLE (table4), checkbutton7, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton8 = gtk_check_button_new_with_label (_("Line 1010 emulator"));
  gtk_widget_set_name (checkbutton8, "checkbutton8");
  gtk_widget_ref (checkbutton8);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton8", checkbutton8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton8);
  gtk_table_attach (GTK_TABLE (table4), checkbutton8, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton2 = gtk_check_button_new_with_label (_("Privilege violation"));
  gtk_widget_set_name (checkbutton2, "checkbutton2");
  gtk_widget_ref (checkbutton2);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton2", checkbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table4), checkbutton2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton9 = gtk_check_button_new_with_label (_("Line 1111 emulator"));
  gtk_widget_set_name (checkbutton9, "checkbutton9");
  gtk_widget_ref (checkbutton9);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton9", checkbutton9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton9);
  gtk_table_attach (GTK_TABLE (table4), checkbutton9, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  frame26 = gtk_frame_new (_("Auto-ints"));
  gtk_widget_set_name (frame26, "frame26");
  gtk_widget_ref (frame26);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "frame26", frame26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame26);
  gtk_table_attach (GTK_TABLE (table3), frame26, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame26), 5);

  vbox33 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox33, "vbox33");
  gtk_widget_ref (vbox33);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "vbox33", vbox33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox33);
  gtk_container_add (GTK_CONTAINER (frame26), vbox33);

  checkbutton10 = gtk_check_button_new_with_label (_("Auto-int 1 (350 Hz timer)"));
  gtk_widget_set_name (checkbutton10, "checkbutton10");
  gtk_widget_ref (checkbutton10);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton10", checkbutton10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton10);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton10, FALSE, FALSE, 0);

  checkbutton11 = gtk_check_button_new_with_label (_("Auto-int 2 (keyboard)"));
  gtk_widget_set_name (checkbutton11, "checkbutton11");
  gtk_widget_ref (checkbutton11);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton11", checkbutton11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton11);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton11, FALSE, FALSE, 0);

  checkbutton12 = gtk_check_button_new_with_label (_("Auto-int 4 (link)"));
  gtk_widget_set_name (checkbutton12, "checkbutton12");
  gtk_widget_ref (checkbutton12);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton12", checkbutton12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton12);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton12, FALSE, FALSE, 0);

  checkbutton13 = gtk_check_button_new_with_label (_("Auto-int 5 (prog timer)"));
  gtk_widget_set_name (checkbutton13, "checkbutton13");
  gtk_widget_ref (checkbutton13);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton13", checkbutton13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton13);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton13, FALSE, FALSE, 0);

  checkbutton15 = gtk_check_button_new_with_label (_("Auto-int 6 (on key)"));
  gtk_widget_set_name (checkbutton15, "checkbutton15");
  gtk_widget_ref (checkbutton15);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton15", checkbutton15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton15);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton15, FALSE, FALSE, 0);

  checkbutton14 = gtk_check_button_new_with_label (_("Auto-int 7 (protected mem)"));
  gtk_widget_set_name (checkbutton14, "checkbutton14");
  gtk_widget_ref (checkbutton14);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton14", checkbutton14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton14);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton14, FALSE, FALSE, 0);

  frame27 = gtk_frame_new (_("Traps"));
  gtk_widget_set_name (frame27, "frame27");
  gtk_widget_ref (frame27);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "frame27", frame27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame27);
  gtk_table_attach (GTK_TABLE (table3), frame27, 0, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame27), 5);

  table5 = gtk_table_new (4, 4, FALSE);
  gtk_widget_set_name (table5, "table5");
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (frame27), table5);

  checkbutton16 = gtk_check_button_new_with_label (_("Trap 0"));
  gtk_widget_set_name (checkbutton16, "checkbutton16");
  gtk_widget_ref (checkbutton16);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton16", checkbutton16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton16);
  gtk_table_attach (GTK_TABLE (table5), checkbutton16, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton17 = gtk_check_button_new_with_label (_("Trap 1 (int mask)"));
  gtk_widget_set_name (checkbutton17, "checkbutton17");
  gtk_widget_ref (checkbutton17);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton17", checkbutton17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton17);
  gtk_table_attach (GTK_TABLE (table5), checkbutton17, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton18 = gtk_check_button_new_with_label (_("Trap 2 (reset)"));
  gtk_widget_set_name (checkbutton18, "checkbutton18");
  gtk_widget_ref (checkbutton18);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton18", checkbutton18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton18);
  gtk_table_attach (GTK_TABLE (table5), checkbutton18, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton19 = gtk_check_button_new_with_label (_("Trap 3"));
  gtk_widget_set_name (checkbutton19, "checkbutton19");
  gtk_widget_ref (checkbutton19);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton19", checkbutton19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton19);
  gtk_table_attach (GTK_TABLE (table5), checkbutton19, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton20 = gtk_check_button_new_with_label (_("Trap 4 (on/off)"));
  gtk_widget_set_name (checkbutton20, "checkbutton20");
  gtk_widget_ref (checkbutton20);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton20", checkbutton20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton20);
  gtk_table_attach (GTK_TABLE (table5), checkbutton20, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton21 = gtk_check_button_new_with_label (_("Trap 5"));
  gtk_widget_set_name (checkbutton21, "checkbutton21");
  gtk_widget_ref (checkbutton21);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton21", checkbutton21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton21);
  gtk_table_attach (GTK_TABLE (table5), checkbutton21, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton22 = gtk_check_button_new_with_label (_("Trap 6"));
  gtk_widget_set_name (checkbutton22, "checkbutton22");
  gtk_widget_ref (checkbutton22);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton22", checkbutton22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton22);
  gtk_table_attach (GTK_TABLE (table5), checkbutton22, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton23 = gtk_check_button_new_with_label (_("Trap 7"));
  gtk_widget_set_name (checkbutton23, "checkbutton23");
  gtk_widget_ref (checkbutton23);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton23", checkbutton23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton23);
  gtk_table_attach (GTK_TABLE (table5), checkbutton23, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton24 = gtk_check_button_new_with_label (_("Trap 8"));
  gtk_widget_set_name (checkbutton24, "checkbutton24");
  gtk_widget_ref (checkbutton24);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton24", checkbutton24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton24);
  gtk_table_attach (GTK_TABLE (table5), checkbutton24, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton25 = gtk_check_button_new_with_label (_("Trap 9"));
  gtk_widget_set_name (checkbutton25, "checkbutton25");
  gtk_widget_ref (checkbutton25);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton25", checkbutton25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton25);
  gtk_table_attach (GTK_TABLE (table5), checkbutton25, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton26 = gtk_check_button_new_with_label (_("Trap 10 (self test)"));
  gtk_widget_set_name (checkbutton26, "checkbutton26");
  gtk_widget_ref (checkbutton26);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton26", checkbutton26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton26);
  gtk_table_attach (GTK_TABLE (table5), checkbutton26, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton27 = gtk_check_button_new_with_label (_("Trap 11 (archive)"));
  gtk_widget_set_name (checkbutton27, "checkbutton27");
  gtk_widget_ref (checkbutton27);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton27", checkbutton27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton27);
  gtk_table_attach (GTK_TABLE (table5), checkbutton27, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton28 = gtk_check_button_new_with_label (_("Trap 12"));
  gtk_widget_set_name (checkbutton28, "checkbutton28");
  gtk_widget_ref (checkbutton28);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton28", checkbutton28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton28);
  gtk_table_attach (GTK_TABLE (table5), checkbutton28, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton29 = gtk_check_button_new_with_label (_("Trap 13"));
  gtk_widget_set_name (checkbutton29, "checkbutton29");
  gtk_widget_ref (checkbutton29);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton29", checkbutton29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton29);
  gtk_table_attach (GTK_TABLE (table5), checkbutton29, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton30 = gtk_check_button_new_with_label (_("Trap 14"));
  gtk_widget_set_name (checkbutton30, "checkbutton30");
  gtk_widget_ref (checkbutton30);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton30", checkbutton30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton30);
  gtk_table_attach (GTK_TABLE (table5), checkbutton30, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton31 = gtk_check_button_new_with_label ("");
  checkbutton31_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (checkbutton31)->child),
                                   _("Trap 15 (ER_throw)"));
  gtk_widget_add_accelerator (checkbutton31, "clicked", accel_group,
                              checkbutton31_key, GDK_MOD1_MASK, 0);
  gtk_widget_set_name (checkbutton31, "checkbutton31");
  gtk_widget_ref (checkbutton31);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "checkbutton31", checkbutton31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton31);
  gtk_table_attach (GTK_TABLE (table5), checkbutton31, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area13 = GTK_DIALOG (trap_dbox)->action_area;
  gtk_widget_set_name (dialog_action_area13, "dialog_action_area13");
  gtk_object_set_data (GTK_OBJECT (trap_dbox), "dialog_action_area13", dialog_action_area13);
  gtk_widget_show (dialog_action_area13);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area13), 10);

  hbuttonbox17 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox17, "hbuttonbox17");
  gtk_widget_ref (hbuttonbox17);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "hbuttonbox17", hbuttonbox17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox17);
  gtk_box_pack_start (GTK_BOX (dialog_action_area13), hbuttonbox17, TRUE, TRUE, 0);

  button46 = gtk_button_new ();
  gtk_widget_set_name (button46, "button46");
  gtk_widget_ref (button46);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "button46", button46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button46);
  gtk_container_add (GTK_CONTAINER (hbuttonbox17), button46);
  GTK_WIDGET_SET_FLAGS (button46, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button46, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (button46), hbox1);

  pixmap1 = create_pixmap (trap_dbox, "yes.xpm");
  gtk_widget_set_name (pixmap1, "pixmap1");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox1), pixmap1, TRUE, FALSE, 0);

  label1 = gtk_label_new ("");
  label1_key = gtk_label_parse_uline (GTK_LABEL (label1),
                                   _("_OK"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 0);

  button47 = gtk_button_new ();
  gtk_widget_set_name (button47, "button47");
  gtk_widget_ref (button47);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "button47", button47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button47);
  gtk_container_add (GTK_CONTAINER (hbuttonbox17), button47);
  GTK_WIDGET_SET_FLAGS (button47, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button47, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (button47), hbox2);

  pixmap2 = create_pixmap (trap_dbox, "no.xpm");
  gtk_widget_set_name (pixmap2, "pixmap2");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap2, TRUE, FALSE, 0);

  label2 = gtk_label_new ("");
  label2_key = gtk_label_parse_uline (GTK_LABEL (label2),
                                   _("_Cancel"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (trap_dbox), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  gtk_signal_connect (GTK_OBJECT (checkbutton1), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton1_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton3), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton3_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton4), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton4_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton5), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton5_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton6), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton6_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton7), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton7_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton8), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton8_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton2), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton2_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton9), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton9_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton10), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton10_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton11), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton11_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton12), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton12_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton13), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton13_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton15), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton15_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton14), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton14_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton16), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton16_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton17), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton17_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton18), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton18_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton19), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton19_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton20), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton20_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton21), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton21_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton22), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton22_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton23), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton23_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton24), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton24_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton25), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton25_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton26), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton26_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton27), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton27_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton28), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton28_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton29), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton29_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton30), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton30_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton31), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton31_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button46), "clicked",
                      GTK_SIGNAL_FUNC (on_button46_clicked),
                      trap_dbox);
  gtk_signal_connect (GTK_OBJECT (button47), "clicked",
                      GTK_SIGNAL_FUNC (on_button47_clicked),
                      trap_dbox);

  gtk_widget_add_accelerator (button46, "clicked", accel_group,
                              label1_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (button47, "clicked", accel_group,
                              label2_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (trap_dbox), accel_group);

  return trap_dbox;
}

