/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "viewlog_cb.h"
#include "viewlog_dbox.h"
#include "support.h"

GtkWidget*
create_viewlog_dbox (void)
{
  GtkWidget *viewlog_dbox;
  GtkWidget *vbox19;
  GtkWidget *vbox20;
  GtkWidget *label22;
  GtkWidget *vbox21;
  GtkWidget *list2;
  GtkWidget *hbox3;
  GtkWidget *hbuttonbox4;
  GtkWidget *button16;
  GtkWidget *button17;
  GtkWidget *button18;
  GtkWidget *button19;
  GtkWidget *button20;

  viewlog_dbox = gtk_dialog_new ();
  gtk_widget_set_name (viewlog_dbox, "viewlog_dbox");
  gtk_object_set_data (GTK_OBJECT (viewlog_dbox), "viewlog_dbox", viewlog_dbox);
  gtk_window_set_title (GTK_WINDOW (viewlog_dbox), _("View log"));

  vbox19 = GTK_DIALOG (viewlog_dbox)->vbox;
  gtk_widget_set_name (vbox19, "vbox19");
  gtk_object_set_data (GTK_OBJECT (viewlog_dbox), "vbox19", vbox19);
  gtk_widget_show (vbox19);

  vbox20 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox20, "vbox20");
  gtk_widget_ref (vbox20);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "vbox20", vbox20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox20);
  gtk_box_pack_start (GTK_BOX (vbox19), vbox20, TRUE, TRUE, 0);

  label22 = gtk_label_new (_("Select new ROM version:"));
  gtk_widget_set_name (label22, "label22");
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (vbox20), label22, FALSE, FALSE, 3);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label22), 10, 0);

  vbox21 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox21, "vbox21");
  gtk_widget_ref (vbox21);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "vbox21", vbox21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox21);
  gtk_box_pack_start (GTK_BOX (vbox20), vbox21, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox21), 7);

  list2 = gtk_list_new ();
  gtk_widget_set_name (list2, "list2");
  gtk_widget_ref (list2);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "list2", list2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (list2);
  gtk_box_pack_start (GTK_BOX (vbox21), list2, TRUE, TRUE, 0);

  hbox3 = GTK_DIALOG (viewlog_dbox)->action_area;
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_object_set_data (GTK_OBJECT (viewlog_dbox), "hbox3", hbox3);
  gtk_widget_show (hbox3);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 10);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox4, "hbuttonbox4");
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (hbox3), hbuttonbox4, FALSE, FALSE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox4), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox4), 0, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox4), 0, 0);

  button16 = gtk_button_new_with_label (_("Edit addresses"));
  gtk_widget_set_name (button16, "button16");
  gtk_widget_ref (button16);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "button16", button16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button16);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  button17 = gtk_button_new_with_label (_("Save text file"));
  gtk_widget_set_name (button17, "button17");
  gtk_widget_ref (button17);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "button17", button17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  button18 = gtk_button_new_with_label (_("Clear log"));
  gtk_widget_set_name (button18, "button18");
  gtk_widget_ref (button18);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "button18", button18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button18);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button18);
  GTK_WIDGET_SET_FLAGS (button18, GTK_CAN_DEFAULT);

  button19 = gtk_button_new_with_label (_("Start logging"));
  gtk_widget_set_name (button19, "button19");
  gtk_widget_ref (button19);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "button19", button19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button19);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button19);
  GTK_WIDGET_SET_FLAGS (button19, GTK_CAN_DEFAULT);

  button20 = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (button20, "button20");
  gtk_widget_ref (button20);
  gtk_object_set_data_full (GTK_OBJECT (viewlog_dbox), "button20", button20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button20);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button20);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);

  return viewlog_dbox;
}

