/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "fsel_cb.h"
#include "fsel_dbox.h"
#include "support.h"

GtkWidget*
create_rom_fileselection (void)
{
  GtkWidget *rom_fileselection;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  rom_fileselection = gtk_file_selection_new (_("Select a ROM to load"));
  gtk_widget_set_name (rom_fileselection, "rom_fileselection");
  gtk_object_set_data (GTK_OBJECT (rom_fileselection), "rom_fileselection", rom_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (rom_fileselection), 10);
  gtk_window_set_modal (GTK_WINDOW (rom_fileselection), TRUE);

  ok_button2 = GTK_FILE_SELECTION (rom_fileselection)->ok_button;
  gtk_widget_set_name (ok_button2, "ok_button2");
  gtk_object_set_data (GTK_OBJECT (rom_fileselection), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (rom_fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button2, "cancel_button2");
  gtk_object_set_data (GTK_OBJECT (rom_fileselection), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (rom_fileselection), "destroy",
                      GTK_SIGNAL_FUNC (on_rom_fileselection_destroy),
                      rom_fileselection);
  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_rom_ok_button2_clicked),
                      rom_fileselection);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_rom_cancel_button2_clicked),
                      rom_fileselection);

  gtk_window_add_accel_group (GTK_WINDOW (rom_fileselection), accel_group);

  return rom_fileselection;
}

GtkWidget*
create_tifile_fileselection (void)
{
  GtkWidget *tifile_fileselection;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  tifile_fileselection = gtk_file_selection_new (_("Select a TI file to load"));
  gtk_widget_set_name (tifile_fileselection, "tifile_fileselection");
  gtk_object_set_data (GTK_OBJECT (tifile_fileselection), "tifile_fileselection", tifile_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (tifile_fileselection), 10);
  gtk_window_set_modal (GTK_WINDOW (tifile_fileselection), TRUE);

  ok_button2 = GTK_FILE_SELECTION (tifile_fileselection)->ok_button;
  gtk_widget_set_name (ok_button2, "ok_button2");
  gtk_object_set_data (GTK_OBJECT (tifile_fileselection), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (tifile_fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button2, "cancel_button2");
  gtk_object_set_data (GTK_OBJECT (tifile_fileselection), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (tifile_fileselection), "destroy",
                      GTK_SIGNAL_FUNC (on_tifile_fileselection_destroy),
                      tifile_fileselection);
  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_tifile_ok_button2_clicked),
                      tifile_fileselection);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_tifile_cancel_button2_clicked),
                      tifile_fileselection);

  gtk_window_add_accel_group (GTK_WINDOW (tifile_fileselection), accel_group);

  return tifile_fileselection;
}

GtkWidget*
create_tib_fileselection (void)
{
  GtkWidget *tib_fileselection;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  tib_fileselection = gtk_file_selection_new (_("Select a FLASH upgrade to load"));
  gtk_widget_set_name (tib_fileselection, "tib_fileselection");
  gtk_object_set_data (GTK_OBJECT (tib_fileselection), "tib_fileselection", tib_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (tib_fileselection), 10);
  gtk_window_set_modal (GTK_WINDOW (tib_fileselection), TRUE);

  ok_button2 = GTK_FILE_SELECTION (tib_fileselection)->ok_button;
  gtk_widget_set_name (ok_button2, "ok_button2");
  gtk_object_set_data (GTK_OBJECT (tib_fileselection), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (tib_fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button2, "cancel_button2");
  gtk_object_set_data (GTK_OBJECT (tib_fileselection), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (tib_fileselection), "destroy",
                      GTK_SIGNAL_FUNC (on_tib_fileselection_destroy),
                      tib_fileselection);
  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_tib_ok_button2_clicked),
                      tib_fileselection);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_tib_cancel_button2_clicked),
                      tib_fileselection);

  gtk_window_add_accel_group (GTK_WINDOW (tib_fileselection), accel_group);

  return tib_fileselection;
}

GtkWidget*
create_ams_fileselection (void)
{
  GtkWidget *ams_fileselection;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  ams_fileselection = gtk_file_selection_new (_("Select a FLASH upgrade to load"));
  gtk_widget_set_name (ams_fileselection, "ams_fileselection");
  gtk_object_set_data (GTK_OBJECT (ams_fileselection), "ams_fileselection", ams_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (ams_fileselection), 10);
  gtk_window_set_modal (GTK_WINDOW (ams_fileselection), TRUE);

  ok_button2 = GTK_FILE_SELECTION (ams_fileselection)->ok_button;
  gtk_widget_set_name (ok_button2, "ok_button2");
  gtk_object_set_data (GTK_OBJECT (ams_fileselection), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (ams_fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button2, "cancel_button2");
  gtk_object_set_data (GTK_OBJECT (ams_fileselection), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (ams_fileselection), "destroy",
                      GTK_SIGNAL_FUNC (on_ams_fileselection_destroy),
                      ams_fileselection);
  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_ams_ok_button2_clicked),
                      ams_fileselection);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_ams_cancel_button2_clicked),
                      ams_fileselection);

  gtk_window_add_accel_group (GTK_WINDOW (ams_fileselection), accel_group);

  return ams_fileselection;
}

