/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "itick_cb.h"
#include "itick_dbox.h"
#include "support.h"

GtkWidget*
create_tickrate_dbox (void)
{
  GtkWidget *tickrate_dbox;
  GtkWidget *dialog_vbox7;
  GtkWidget *frame20;
  GtkWidget *vbox28;
  GtkWidget *label29;
  GtkWidget *hbox8;
  GtkWidget *label30;
  GtkWidget *entry7;
  GtkWidget *dialog_action_area7;
  GtkWidget *hbuttonbox10;
  GtkWidget *button33;
  GtkWidget *hbox12;
  GtkWidget *pixmap1;
  guint label49_key;
  GtkWidget *label49;
  GtkWidget *button34;
  GtkWidget *hbox13;
  GtkWidget *pixmap2;
  guint label50_key;
  GtkWidget *label50;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  tickrate_dbox = gtk_dialog_new ();
  gtk_widget_set_name (tickrate_dbox, "tickrate_dbox");
  gtk_object_set_data (GTK_OBJECT (tickrate_dbox), "tickrate_dbox", tickrate_dbox);
  gtk_window_set_title (GTK_WINDOW (tickrate_dbox), _("TickRate"));
  gtk_window_set_policy (GTK_WINDOW (tickrate_dbox), FALSE, FALSE, FALSE);

  dialog_vbox7 = GTK_DIALOG (tickrate_dbox)->vbox;
  gtk_widget_set_name (dialog_vbox7, "dialog_vbox7");
  gtk_object_set_data (GTK_OBJECT (tickrate_dbox), "dialog_vbox7", dialog_vbox7);
  gtk_widget_show (dialog_vbox7);

  frame20 = gtk_frame_new (_("Tickrate (timer rate)"));
  gtk_widget_set_name (frame20, "frame20");
  gtk_widget_ref (frame20);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "frame20", frame20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame20);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), frame20, TRUE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (frame20), 5);

  vbox28 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox28, "vbox28");
  gtk_widget_ref (vbox28);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "vbox28", vbox28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox28);
  gtk_container_add (GTK_CONTAINER (frame20), vbox28);

  label29 = gtk_label_new (_("Set number the rate of the timer. The higher the slower."));
  gtk_widget_set_name (label29, "label29");
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (vbox28), label29, FALSE, FALSE, 5);
  gtk_label_set_line_wrap (GTK_LABEL (label29), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label29), 10, 0);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox28), hbox8, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox8), 10);

  label30 = gtk_label_new (_("Tickrate :"));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox8), label30, TRUE, TRUE, 5);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label30), 7.45058e-09, 0.5);
  gtk_misc_set_padding (GTK_MISC (label30), 5, 0);

  entry7 = gtk_entry_new_with_max_length (10);
  gtk_widget_set_name (entry7, "entry7");
  gtk_widget_ref (entry7);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "entry7", entry7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry7);
  gtk_box_pack_start (GTK_BOX (hbox8), entry7, TRUE, TRUE, 5);
  gtk_widget_set_usize (entry7, 100, -2);
  gtk_entry_set_text (GTK_ENTRY (entry7), _("40000"));

  dialog_action_area7 = GTK_DIALOG (tickrate_dbox)->action_area;
  gtk_widget_set_name (dialog_action_area7, "dialog_action_area7");
  gtk_object_set_data (GTK_OBJECT (tickrate_dbox), "dialog_action_area7", dialog_action_area7);
  gtk_widget_show (dialog_action_area7);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area7), 10);

  hbuttonbox10 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox10, "hbuttonbox10");
  gtk_widget_ref (hbuttonbox10);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "hbuttonbox10", hbuttonbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox10);
  gtk_box_pack_start (GTK_BOX (dialog_action_area7), hbuttonbox10, TRUE, TRUE, 0);

  button33 = gtk_button_new ();
  gtk_widget_set_name (button33, "button33");
  gtk_widget_ref (button33);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "button33", button33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button33);
  gtk_container_add (GTK_CONTAINER (hbuttonbox10), button33);
  GTK_WIDGET_SET_FLAGS (button33, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button33, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox12 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_ref (hbox12);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "hbox12", hbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (button33), hbox12);

  pixmap1 = create_pixmap (tickrate_dbox, "yes.xpm");
  gtk_widget_set_name (pixmap1, "pixmap1");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox12), pixmap1, TRUE, FALSE, 0);

  label49 = gtk_label_new ("");
  label49_key = gtk_label_parse_uline (GTK_LABEL (label49),
                                   _("_OK"));
  gtk_widget_set_name (label49, "label49");
  gtk_widget_ref (label49);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "label49", label49,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox12), label49, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label49), 5, 0);

  button34 = gtk_button_new ();
  gtk_widget_set_name (button34, "button34");
  gtk_widget_ref (button34);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "button34", button34,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button34);
  gtk_container_add (GTK_CONTAINER (hbuttonbox10), button34);
  GTK_WIDGET_SET_FLAGS (button34, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button34, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_ref (hbox13);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "hbox13", hbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (button34), hbox13);

  pixmap2 = create_pixmap (tickrate_dbox, "no.xpm");
  gtk_widget_set_name (pixmap2, "pixmap2");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox13), pixmap2, TRUE, FALSE, 0);

  label50 = gtk_label_new ("");
  label50_key = gtk_label_parse_uline (GTK_LABEL (label50),
                                   _("_Cancel"));
  gtk_widget_set_name (label50, "label50");
  gtk_widget_ref (label50);
  gtk_object_set_data_full (GTK_OBJECT (tickrate_dbox), "label50", label50,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox13), label50, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label50), 5, 0);

  gtk_signal_connect (GTK_OBJECT (tickrate_dbox), "destroy",
                      GTK_SIGNAL_FUNC (on_tickrate_dbox_destroy),
                      tickrate_dbox);
  gtk_signal_connect (GTK_OBJECT (entry7), "changed",
                      GTK_SIGNAL_FUNC (on_entry7_changed),
                      entry7);
  gtk_signal_connect (GTK_OBJECT (button33), "clicked",
                      GTK_SIGNAL_FUNC (on_button33_clicked),
                      tickrate_dbox);
  gtk_signal_connect (GTK_OBJECT (button34), "clicked",
                      GTK_SIGNAL_FUNC (on_button34_clicked),
                      tickrate_dbox);

  gtk_widget_add_accelerator (button33, "clicked", accel_group,
                              label49_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (button34, "clicked", accel_group,
                              label50_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (tickrate_dbox), accel_group);

  return tickrate_dbox;
}

GtkWidget*
create_cyclerate_dbox (void)
{
  GtkWidget *cyclerate_dbox;
  GtkWidget *dialog_vbox8;
  GtkWidget *frame21;
  GtkWidget *vbox29;
  GtkWidget *label31;
  GtkWidget *hbox9;
  GtkWidget *label32;
  GtkWidget *entry8;
  GtkWidget *dialog_action_area8;
  GtkWidget *hbuttonbox11;
  GtkWidget *button35;
  GtkWidget *hbox14;
  GtkWidget *pixmap3;
  guint label51_key;
  GtkWidget *label51;
  GtkWidget *button36;
  GtkWidget *hbox15;
  GtkWidget *pixmap4;
  guint label52_key;
  GtkWidget *label52;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  cyclerate_dbox = gtk_dialog_new ();
  gtk_widget_set_name (cyclerate_dbox, "cyclerate_dbox");
  gtk_object_set_data (GTK_OBJECT (cyclerate_dbox), "cyclerate_dbox", cyclerate_dbox);
  gtk_window_set_title (GTK_WINDOW (cyclerate_dbox), _("Cycle Rate"));
  gtk_window_set_policy (GTK_WINDOW (cyclerate_dbox), FALSE, FALSE, FALSE);

  dialog_vbox8 = GTK_DIALOG (cyclerate_dbox)->vbox;
  gtk_widget_set_name (dialog_vbox8, "dialog_vbox8");
  gtk_object_set_data (GTK_OBJECT (cyclerate_dbox), "dialog_vbox8", dialog_vbox8);
  gtk_widget_show (dialog_vbox8);

  frame21 = gtk_frame_new (_("Cycle rate"));
  gtk_widget_set_name (frame21, "frame21");
  gtk_widget_ref (frame21);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "frame21", frame21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame21);
  gtk_box_pack_start (GTK_BOX (dialog_vbox8), frame21, TRUE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (frame21), 5);

  vbox29 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox29, "vbox29");
  gtk_widget_ref (vbox29);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "vbox29", vbox29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox29);
  gtk_container_add (GTK_CONTAINER (frame21), vbox29);

  label31 = gtk_label_new (_("Set the rate of instructions."));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (vbox29), label31, FALSE, FALSE, 5);
  gtk_label_set_line_wrap (GTK_LABEL (label31), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label31), 10, 0);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox9, "hbox9");
  gtk_widget_ref (hbox9);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "hbox9", hbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox29), hbox9, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox9), 10);

  label32 = gtk_label_new (_("Cyclerate :"));
  gtk_widget_set_name (label32, "label32");
  gtk_widget_ref (label32);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "label32", label32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox9), label32, TRUE, TRUE, 5);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label32), 5, 0);

  entry8 = gtk_entry_new_with_max_length (6);
  gtk_widget_set_name (entry8, "entry8");
  gtk_widget_ref (entry8);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "entry8", entry8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry8);
  gtk_box_pack_start (GTK_BOX (hbox9), entry8, TRUE, TRUE, 5);
  gtk_widget_set_usize (entry8, 100, -2);
  gtk_entry_set_text (GTK_ENTRY (entry8), _("140"));

  dialog_action_area8 = GTK_DIALOG (cyclerate_dbox)->action_area;
  gtk_widget_set_name (dialog_action_area8, "dialog_action_area8");
  gtk_object_set_data (GTK_OBJECT (cyclerate_dbox), "dialog_action_area8", dialog_action_area8);
  gtk_widget_show (dialog_action_area8);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area8), 10);

  hbuttonbox11 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox11, "hbuttonbox11");
  gtk_widget_ref (hbuttonbox11);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "hbuttonbox11", hbuttonbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox11);
  gtk_box_pack_start (GTK_BOX (dialog_action_area8), hbuttonbox11, TRUE, TRUE, 0);

  button35 = gtk_button_new ();
  gtk_widget_set_name (button35, "button35");
  gtk_widget_ref (button35);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "button35", button35,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button35);
  gtk_container_add (GTK_CONTAINER (hbuttonbox11), button35);
  GTK_WIDGET_SET_FLAGS (button35, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button35, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox14 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox14, "hbox14");
  gtk_widget_ref (hbox14);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "hbox14", hbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (button35), hbox14);

  pixmap3 = create_pixmap (cyclerate_dbox, "yes.xpm");
  gtk_widget_set_name (pixmap3, "pixmap3");
  gtk_widget_ref (pixmap3);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "pixmap3", pixmap3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap3);
  gtk_box_pack_start (GTK_BOX (hbox14), pixmap3, TRUE, FALSE, 0);

  label51 = gtk_label_new ("");
  label51_key = gtk_label_parse_uline (GTK_LABEL (label51),
                                   _("_OK"));
  gtk_widget_set_name (label51, "label51");
  gtk_widget_ref (label51);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "label51", label51,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox14), label51, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label51), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label51), 5, 0);

  button36 = gtk_button_new ();
  gtk_widget_set_name (button36, "button36");
  gtk_widget_ref (button36);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "button36", button36,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button36);
  gtk_container_add (GTK_CONTAINER (hbuttonbox11), button36);
  GTK_WIDGET_SET_FLAGS (button36, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button36, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox15, "hbox15");
  gtk_widget_ref (hbox15);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "hbox15", hbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (button36), hbox15);

  pixmap4 = create_pixmap (cyclerate_dbox, "no.xpm");
  gtk_widget_set_name (pixmap4, "pixmap4");
  gtk_widget_ref (pixmap4);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "pixmap4", pixmap4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap4);
  gtk_box_pack_start (GTK_BOX (hbox15), pixmap4, TRUE, FALSE, 0);

  label52 = gtk_label_new ("");
  label52_key = gtk_label_parse_uline (GTK_LABEL (label52),
                                   _("_Cancel"));
  gtk_widget_set_name (label52, "label52");
  gtk_widget_ref (label52);
  gtk_object_set_data_full (GTK_OBJECT (cyclerate_dbox), "label52", label52,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox15), label52, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label52), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label52), 5, 0);

  gtk_signal_connect (GTK_OBJECT (cyclerate_dbox), "destroy",
                      GTK_SIGNAL_FUNC (on_cyclerate_dbox_destroy),
                      cyclerate_dbox);
  gtk_signal_connect (GTK_OBJECT (entry8), "changed",
                      GTK_SIGNAL_FUNC (on_entry8_changed),
                      entry8);
  gtk_signal_connect (GTK_OBJECT (button35), "clicked",
                      GTK_SIGNAL_FUNC (on_button35_clicked),
                      cyclerate_dbox);
  gtk_signal_connect (GTK_OBJECT (button36), "clicked",
                      GTK_SIGNAL_FUNC (on_button36_clicked),
                      cyclerate_dbox);

  gtk_widget_add_accelerator (button35, "clicked", accel_group,
                              label51_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (button36, "clicked", accel_group,
                              label52_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (cyclerate_dbox), accel_group);

  return cyclerate_dbox;
}

GtkWidget*
create_itick_dbox (void)
{
  GtkWidget *itick_dbox;
  GtkWidget *dialog_vbox9;
  GtkWidget *frame23;
  GtkWidget *vbox32;
  GtkWidget *label47;
  GtkWidget *hbox11;
  GtkWidget *label48;
  GtkWidget *entry9;
  GtkWidget *dialog_action_area9;
  GtkWidget *hbuttonbox13;
  GtkWidget *button41;
  GtkWidget *hbox16;
  GtkWidget *pixmap5;
  guint label53_key;
  GtkWidget *label53;
  GtkWidget *button42;
  GtkWidget *hbox17;
  GtkWidget *pixmap6;
  guint label54_key;
  GtkWidget *label54;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  itick_dbox = gtk_dialog_new ();
  gtk_widget_set_name (itick_dbox, "itick_dbox");
  gtk_object_set_data (GTK_OBJECT (itick_dbox), "itick_dbox", itick_dbox);
  gtk_window_set_title (GTK_WINDOW (itick_dbox), _("itick"));
  gtk_window_set_policy (GTK_WINDOW (itick_dbox), FALSE, FALSE, FALSE);

  dialog_vbox9 = GTK_DIALOG (itick_dbox)->vbox;
  gtk_widget_set_name (dialog_vbox9, "dialog_vbox9");
  gtk_object_set_data (GTK_OBJECT (itick_dbox), "dialog_vbox9", dialog_vbox9);
  gtk_widget_show (dialog_vbox9);

  frame23 = gtk_frame_new (_("itick:"));
  gtk_widget_set_name (frame23, "frame23");
  gtk_widget_ref (frame23);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "frame23", frame23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame23);
  gtk_box_pack_start (GTK_BOX (dialog_vbox9), frame23, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame23), 5);

  vbox32 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox32, "vbox32");
  gtk_widget_ref (vbox32);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "vbox32", vbox32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox32);
  gtk_container_add (GTK_CONTAINER (frame23), vbox32);

  label47 = gtk_label_new (_("Set number the rate of the timer. The higher the slower."));
  gtk_widget_set_name (label47, "label47");
  gtk_widget_ref (label47);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "label47", label47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (vbox32), label47, FALSE, FALSE, 5);
  gtk_label_set_line_wrap (GTK_LABEL (label47), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label47), 10, 0);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_ref (hbox11);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "hbox11", hbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox32), hbox11, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox11), 10);

  label48 = gtk_label_new (_("ITick :"));
  gtk_widget_set_name (label48, "label48");
  gtk_widget_ref (label48);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "label48", label48,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox11), label48, TRUE, TRUE, 5);
  gtk_label_set_justify (GTK_LABEL (label48), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label48), 7.45058e-09, 0.5);
  gtk_misc_set_padding (GTK_MISC (label48), 5, 0);

  entry9 = gtk_entry_new_with_max_length (10);
  gtk_widget_set_name (entry9, "entry9");
  gtk_widget_ref (entry9);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "entry9", entry9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry9);
  gtk_box_pack_start (GTK_BOX (hbox11), entry9, TRUE, TRUE, 5);
  gtk_widget_set_usize (entry9, 100, -2);
  gtk_entry_set_text (GTK_ENTRY (entry9), _("640"));

  dialog_action_area9 = GTK_DIALOG (itick_dbox)->action_area;
  gtk_widget_set_name (dialog_action_area9, "dialog_action_area9");
  gtk_object_set_data (GTK_OBJECT (itick_dbox), "dialog_action_area9", dialog_action_area9);
  gtk_widget_show (dialog_action_area9);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area9), 10);

  hbuttonbox13 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox13, "hbuttonbox13");
  gtk_widget_ref (hbuttonbox13);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "hbuttonbox13", hbuttonbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox13);
  gtk_box_pack_start (GTK_BOX (dialog_action_area9), hbuttonbox13, TRUE, TRUE, 0);

  button41 = gtk_button_new ();
  gtk_widget_set_name (button41, "button41");
  gtk_widget_ref (button41);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "button41", button41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button41);
  gtk_container_add (GTK_CONTAINER (hbuttonbox13), button41);
  GTK_WIDGET_SET_FLAGS (button41, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button41, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox16 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox16, "hbox16");
  gtk_widget_ref (hbox16);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "hbox16", hbox16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (button41), hbox16);

  pixmap5 = create_pixmap (itick_dbox, "yes.xpm");
  gtk_widget_set_name (pixmap5, "pixmap5");
  gtk_widget_ref (pixmap5);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "pixmap5", pixmap5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap5);
  gtk_box_pack_start (GTK_BOX (hbox16), pixmap5, TRUE, FALSE, 0);

  label53 = gtk_label_new ("");
  label53_key = gtk_label_parse_uline (GTK_LABEL (label53),
                                   _("_OK"));
  gtk_widget_set_name (label53, "label53");
  gtk_widget_ref (label53);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "label53", label53,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox16), label53, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label53), 5, 0);

  button42 = gtk_button_new ();
  gtk_widget_set_name (button42, "button42");
  gtk_widget_ref (button42);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "button42", button42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button42);
  gtk_container_add (GTK_CONTAINER (hbuttonbox13), button42);
  GTK_WIDGET_SET_FLAGS (button42, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button42, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox17, "hbox17");
  gtk_widget_ref (hbox17);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "hbox17", hbox17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (button42), hbox17);

  pixmap6 = create_pixmap (itick_dbox, "no.xpm");
  gtk_widget_set_name (pixmap6, "pixmap6");
  gtk_widget_ref (pixmap6);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "pixmap6", pixmap6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap6);
  gtk_box_pack_start (GTK_BOX (hbox17), pixmap6, TRUE, FALSE, 0);

  label54 = gtk_label_new ("");
  label54_key = gtk_label_parse_uline (GTK_LABEL (label54),
                                   _("_Cancel"));
  gtk_widget_set_name (label54, "label54");
  gtk_widget_ref (label54);
  gtk_object_set_data_full (GTK_OBJECT (itick_dbox), "label54", label54,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox17), label54, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label54), 5, 0);

  gtk_signal_connect (GTK_OBJECT (itick_dbox), "destroy",
                      GTK_SIGNAL_FUNC (on_itick_dbox_destroy),
                      itick_dbox);
  gtk_signal_connect (GTK_OBJECT (entry9), "changed",
                      GTK_SIGNAL_FUNC (on_entry9_changed),
                      entry9);
  gtk_signal_connect (GTK_OBJECT (button41), "clicked",
                      GTK_SIGNAL_FUNC (on_button41_clicked),
                      itick_dbox);
  gtk_signal_connect (GTK_OBJECT (button42), "clicked",
                      GTK_SIGNAL_FUNC (on_button42_clicked),
                      itick_dbox);

  gtk_widget_add_accelerator (button41, "clicked", accel_group,
                              label53_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (button42, "clicked", accel_group,
                              label54_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (itick_dbox), accel_group);

  return itick_dbox;
}

