/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "logaddr_cb.h"
#include "logaddr_dbox.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_edit_logged_addr_dbox (void)
{
  GtkWidget *edit_logged_addr_dbox;
  GtkWidget *dialog_vbox4;
  GtkWidget *list4;
  GtkWidget *dialog_action_area4;
  GtkWidget *hbuttonbox7;
  GtkWidget *button26;
  GtkWidget *button27;
  GtkWidget *button28;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  edit_logged_addr_dbox = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (edit_logged_addr_dbox), _("Edit logged addresses"));

  dialog_vbox4 = GTK_DIALOG (edit_logged_addr_dbox)->vbox;
  gtk_widget_show (dialog_vbox4);

  list4 = gtk_tree_view_new ();
  gtk_widget_show (list4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), list4, TRUE, TRUE, 10);
  GTK_WIDGET_UNSET_FLAGS (list4, GTK_CAN_FOCUS);

  dialog_action_area4 = GTK_DIALOG (edit_logged_addr_dbox)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox7);
  gtk_container_add (GTK_CONTAINER (dialog_action_area4), hbuttonbox7);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox7), 30);

  button26 = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_show (button26);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button26);
  GTK_WIDGET_SET_FLAGS (button26, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button26, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  button27 = gtk_button_new_from_stock ("gtk-delete");
  gtk_widget_show (button27);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button27);
  GTK_WIDGET_SET_FLAGS (button27, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button27, "clicked", accel_group,
                              GDK_Delete, 0,
                              GTK_ACCEL_VISIBLE);

  button28 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button28);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button28);
  GTK_WIDGET_SET_FLAGS (button28, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button28, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (edit_logged_addr_dbox, edit_logged_addr_dbox, "edit_logged_addr_dbox");
  GLADE_HOOKUP_OBJECT_NO_REF (edit_logged_addr_dbox, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (edit_logged_addr_dbox, list4, "list4");
  GLADE_HOOKUP_OBJECT_NO_REF (edit_logged_addr_dbox, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (edit_logged_addr_dbox, hbuttonbox7, "hbuttonbox7");
  GLADE_HOOKUP_OBJECT (edit_logged_addr_dbox, button26, "button26");
  GLADE_HOOKUP_OBJECT (edit_logged_addr_dbox, button27, "button27");
  GLADE_HOOKUP_OBJECT (edit_logged_addr_dbox, button28, "button28");

  gtk_window_add_accel_group (GTK_WINDOW (edit_logged_addr_dbox), accel_group);

  return edit_logged_addr_dbox;
}

